#!/usr/bin/env python3
"""
scripts/pilot_builder/generate_accounting_bank.py
Generates exactly 200 authoritative canonical accounting learning entries
with professional Vietnamese translations, English mappings, PRO difficulty,
priority scores, collocations, natural workplace examples, and dialogues.
"""

import json
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent.parent
OUTPUT_FILE = BASE_DIR / "scripts" / "pilot_builder" / "accounting_data.py"

# Definition of 200 terms data tuples:
# (surface, reading, romaji, vi_short, vi_explanation, en_pref, tier, priority, [examples], [dialogue], [collocations], [related])
RAW_ACCOUNTING_200 = [
    # Statements & Foundations (1-10)
    ("貸借対照表", "たいしゃくたいしょうひょう", "taishakutaishouhyou", "bảng cân đối kế toán", "Báo cáo tài chính phản ánh tổng thể tài sản, nợ phải trả và vốn chủ sở hữu của doanh nghiệp tại thời điểm khóa sổ.", "Balance sheet", "PRO-A1", 98, [("決算月に貸借対照表を作成し、財務の健全性を確認します。", "Vào tháng quyết toán, chúng tôi lập bảng cân đối kế toán để kiểm tra độ lành mạnh tài chính.", "We prepare the balance sheet during the closing month to verify financial soundness.")], [("A", "最新の貸借対照表を見せていただけますか。", "Anh có thể cho tôi xem bảng cân đối kế toán mới nhất được không?", "Could you please show me the latest balance sheet?"), ("B", "はい、先月締め分のB/Sをご用意しました。", "Vâng, tôi đã chuẩn bị sẵn B/S của kỳ chốt sổ tháng trước rồi ạ.", "Yes, I have prepared the balance sheet from last month's closing.")], ["貸借対照表を作成する", "B/S分析"], ["損益計算書", "資産", "負債"]),
    ("損益計算書", "そんえきけいさんしょ", "sonekkikeisansho", "báo cáo kết quả hoạt động kinh doanh", "Báo cáo tài chính tổng hợp toàn bộ doanh thu, chi phí và lợi nhuận hoặc lỗ của doanh nghiệp trong một kỳ kế toán.", "Income statement", "PRO-A1", 98, [("月次損益計算書を確認して、各部門の利益率を把握します。", "Chúng tôi kiểm tra báo cáo kết quả kinh doanh hàng tháng để nắm bắt tỷ suất lợi nhuận của từng bộ phận.", "We review the monthly income statement to monitor profit margins by department.")], [("Manager", "今期の損益計算書で営業利益はどうなっていますか。", "Lợi nhuận kinh doanh trên báo cáo kết quả kinh doanh kỳ này thế nào?", "How is the operating profit looking on this period's income statement?"), ("Staff", "原価削減により前年比で15％増加しています。", "Nhờ cắt giảm giá vốn nên đã tăng 15% so với năm ngoái ạ.", "Due to cost reductions, it is up 15% year-on-year.")], ["損益計算書を分析する", "P/L管理"], ["貸借対照表", "売上高", "営業利益"]),
    ("キャッシュ・フロー計算書", "きゃっしゅふろーけいさんしょ", "kyasshufuro-keisansho", "báo cáo lưu chuyển tiền tệ", "Báo cáo tài chính phản ánh dòng tiền vào và ra thực tế trong kỳ từ hoạt động kinh doanh, đầu tư và tài chính.", "Cash flow statement", "PRO-A2", 95, [("黒字倒産を防ぐため、キャッシュ・フロー計算書を常に注視する。", "Để phòng ngừa phá sản trong lúc có lãi, chúng tôi luôn theo dõi sát báo cáo lưu chuyển tiền tệ.", "To prevent bankruptcy while profitable, we always closely monitor the cash flow statement.")], [], ["営業CFの黒字化", "フリーキャッシュフロー"], ["損益計算書", "資金繰り表"]),
    ("株主資本等変動計算書", "かぶぬししほんとうへんどうけいさんしょ", "kabunushishihontouhendoukeisansho", "báo cáo biến động vốn chủ sở hữu", "Báo cáo tài chính chi tiết biến động của từng khoản mục vốn chủ sở hữu trong kỳ kế toán.", "Statement of changes in equity", "PRO-A3", 88, [("株主総会提出資料に株主資本等変動計算書を添付する。", "Đính kèm báo cáo biến động vốn chủ sở hữu vào tài liệu trình đại hội đồng cổ đông.", "Attach the statement of changes in equity to the materials submitted to the general meeting of shareholders.")], [], ["資本の変動", "剰余金の配当"], ["資本金", "利益剰余金"]),
    ("附属明細表", "ふぞくめいさいひょう", "fuzokumeisaihyou", "bảng thuyết minh chi tiết kèm theo báo cáo tài chính", "Tài liệu chi tiết kèm theo báo cáo tài chính thuyết minh cụ thể về tài sản cố định, nợ vay, vốn chủ sở hữu.", "Supplementary schedules", "PRO-A3", 85, [("有価証券報告書に固定資産の附属明細表を記載する。", "Ghi bảng thuyết minh chi tiết tài sản cố định vào báo cáo chứng khoán.", "Record the supplementary schedule of fixed assets in the securities report.")], [], ["明細表を作成する", "注記情報"], ["有価証券報告書"]),
    ("連結財務諸表", "れんけつざいむしょひょう", "renketsuzaimushohyou", "báo cáo tài chính hợp nhất", "Báo cáo tài chính phản ánh tình hình tài chính và kết quả kinh doanh của toàn bộ tập đoàn gồm công ty mẹ và các công ty con.", "Consolidated financial statements", "PRO-A2", 94, [("グローバル企業として連結財務諸表の開示が義務付けられている。", "Là doanh nghiệp toàn cầu, công ty chúng tôi có nghĩa vụ công bố báo cáo tài chính hợp nhất.", "As a global enterprise, we are required to disclose consolidated financial statements.")], [], ["連結ベースでの決算", "連結子会社"], ["個別財務諸表", "持分法"]),
    ("個別財務諸表", "こべつざいむしょひょう", "kobetuzaimushohyou", "báo cáo tài chính riêng lẻ / công ty mẹ", "Báo cáo tài chính phản ánh độc lập tình hình tài chính của riêng pháp nhân công ty mẹ.", "Non-consolidated financial statements", "PRO-A2", 90, [("税務申告は個別財務諸表の数値をベースに行われます。", "Khai quyết toán thuế được tiến hành dựa trên số liệu của báo cáo tài chính riêng lẻ.", "Tax filings are conducted based on the figures of non-consolidated financial statements.")], [], ["単体決算", "個別損益"], ["連結財務諸表"]),
    ("四半期報告書", "しはんきほうこくしょ", "shihankihoukokusho", "báo cáo tài chính quý", "Báo cáo tài chính định kỳ 3 tháng được các công ty niêm yết lập và công bố ra công chúng.", "Quarterly financial report", "PRO-A2", 92, [("第2四半期報告書を適時開示システムで公表した。", "Đã công bố báo cáo quý 2 qua hệ thống công bố thông tin kịp thời.", "We announced the second-quarter report through the timely disclosure system.")], [], ["四半期決算", "適時開示"], ["有価証券報告書", "決算短信"]),
    ("決算短信", "けっさんたんしん", "kesshantanshin", "bản tóm tắt kết quả kinh doanh", "Bản tóm tắt kết quả tài chính nhanh do các công ty niêm yết tại Nhật Bản công bố cho sàn giao dịch ngay sau khi chốt số liệu.", "Financial results summary", "PRO-A2", 93, [("東京証券取引所へ本決算の決算短信を提出しました。", "Chúng tôi đã nộp bản tóm tắt kết quả quyết toán năm lên Sở giao dịch chứng khoán Tokyo.", "We submitted the annual financial results summary to the Tokyo Stock Exchange.")], [], ["短信を発表する", "業績予想"], ["有価証券報告書"]),
    ("有価証券報告書", "ゆうかしょうけんほうこくしょ", "yuukashoukenhoukokusho", "báo cáo chứng khoán hàng năm (Yukaho)", "Báo cáo thường niên toàn diện nhất theo Luật Giao dịch Công cụ Tài chính Nhật Bản nộp cho Cục Tài chính địa phương.", "Annual securities report", "PRO-A2", 94, [("有価証券報告書はEDINETを通じて電子提出されます。", "Báo cáo chứng khoán hàng năm được nộp điện tử qua hệ thống EDINET.", "The annual securities report is submitted electronically via EDINET.")], [], ["有報を提出する", "EDINET開示"], ["決算短信", "金融商品取引法"]),

    # Current Assets (11-40)
    ("現金及び預金", "げんきんおよびよきん", "genkinooyobiyokin", "tiền mặt và tiền gửi ngân hàng", "Khoản mục phản ánh tổng tiền mặt tại quỹ và các tài khoản tiền gửi tại các tổ chức tín dụng.", "Cash and deposits", "PRO-A1", 97, [("現金及び預金の残高が3か月分の固定費を下回らないよう管理する。", "Quản lý sao cho số dư tiền mặt và tiền gửi không thấp hơn 3 tháng chi phí cố định.", "Manage cash and deposits so that balances do not fall below three months of fixed costs.")], [], ["現預金残高", "手元流動性"], ["当座預金", "普通預金"]),
    ("当座預金", "とうざよきん", "touzayokin", "tiền gửi vãng lai / tiền gửi thanh toán", "Tài khoản tiền gửi không kỳ hạn tại ngân hàng, không phát sinh lãi, dùng để thanh toán séc và hối phiếu.", "Current account / Checking account", "PRO-A1", 96, [("当座預金口座を開設して、手形決済に備えます。", "Mở tài khoản tiền gửi vãng lai để phục vụ thanh toán thương phiếu.", "Open a checking account in preparation for bill settlements.")], [], ["当座預金勘定", "当座照合表"], ["普通預金", "小切手", "手形"]),
    ("普通預金", "ふつうよきん", "futsuuyokin", "tiền gửi thanh toán thông thường", "Tài khoản tiền gửi ngân hàng phổ biến nhất của doanh nghiệp, có thể gửi và rút bất kỳ lúc nào và được nhận lãi định kỳ.", "Ordinary deposit / Savings deposit", "PRO-A1", 98, [("売掛金の入金口座として普通預金を使用しています。", "Chúng tôi sử dụng tài khoản tiền gửi thông thường làm tài khoản nhận tiền thanh toán công nợ.", "We use an ordinary deposit account as the collection account for receivables.")], [], ["普通預金口座", "口座振替"], ["当座預金", "振込"]),
    ("定期預金", "ていきよきん", "teikiyokin", "tiền gửi tiết kiệm có kỳ hạn", "Khoản tiền gửi ngân hàng có kỳ hạn cố định, hưởng lãi suất cao hơn tiền gửi thông thường và không thể rút tự do trước hạn.", "Time deposit / Term deposit", "PRO-A1", 90, [("余裕資金を1年物の定期預金として運用する。", "Sử dụng dòng tiền nhàn rỗi để gửi tiết kiệm kỳ hạn 1 năm.", "Invest surplus funds into a one-year time deposit.")], [], ["定期預金を解約する", "満期受取"], ["普通預金", "受取利息"]),
    ("売掛金", "うりかけきん", "urikakekin", "khoản phải thu khách hàng", "Khoản tiền phát sinh từ việc bán hàng hóa, dịch vụ cho khách hàng mà doanh nghiệp chưa thu được tiền.", "Accounts receivable - trade", "PRO-A1", 99, [("月末に売掛金の残高を確認し、未収がないか照合します。", "Cuối tháng chúng tôi kiểm tra số dư khoản phải thu và đối chiếu xem còn khoản nào chưa về không.", "At the end of the month, we check the accounts receivable balance to see if any are uncollected.")], [("A", "この売掛金の回収期日はいつですか。", "Thời hạn thu hồi khoản phải thu này là khi nào?", "When is the collection due date for this receivable?"), ("B", "来月末の予定となっております。", "Dự kiến là cuối tháng sau ạ.", "It is scheduled for the end of next month.")], ["売掛金を回収する", "売掛金残高", "売掛金元帳"], ["買掛金", "受取手形", "売上債権"]),
    ("受取手形", "うけとりてがた", "uketoritegata", "thương phiếu phải thu", "Kỳ phiếu hoặc hối phiếu do khách hàng phát hành cam kết thanh toán tiền mua hàng khi đến hạn.", "Notes receivable - trade", "PRO-A2", 92, [("受取手形を期日前に銀行で割り引いて資金化した。", "Chiết khấu thương phiếu phải thu tại ngân hàng trước ngày đáo hạn để chuyển thành tiền mặt.", "Discounted notes receivable at the bank before maturity to monetize them.")], [], ["手形割引", "満期日", "手形期日"], ["支払手形", "売掛金"]),
    ("電子記録債権", "でんしきろくさいけん", "denshikirokusaiken", "chứng từ nợ điện tử phải thu (Densai)", "Quyền đòi nợ được đăng ký điện tử thông qua tổ chức đăng ký (Densai Net), thay thế cho hối phiếu giấy truyền thống.", "Electronically recorded monetary claims", "PRO-A2", 93, [("紙の手形廃止に伴い、電子記録債権の利用を開始した。", "Theo lộ trình bãi bỏ hối phiếu giấy, chúng tôi đã bắt đầu sử dụng chứng từ nợ điện tử.", "Following the discontinuation of paper notes, we began using electronically recorded monetary claims.")], [], ["でんさいネット", "電子債権決済"], ["電子記録債務", "受取手形"]),
    ("売上債権", "うりあげさいけん", "uriagesaiken", "nợ phải thu thương mại", "Thuật ngữ chung chỉ toàn bộ các khoản phải thu phát sinh trực tiếp từ hoạt động bán hàng (gồm cả 売掛金 và 受取手形).", "Trade receivables", "PRO-A2", 95, [("売上債権回転期間を短縮して資金効率を高める。", "Rút ngắn vòng quay nợ phải thu thương mại để nâng cao hiệu quả sử dụng vốn.", "Shorten the trade receivables turnover period to enhance capital efficiency.")], [], ["売上債権回転率", "債権回収"], ["仕入債務", "売掛金"]),
    ("有価証券", "ゆうかしょうけん", "yuukashouken", "chứng khoán ngắn hạn", "Các loại cổ phiếu, trái phiếu do doanh nghiệp nắm giữ với mục đích đầu tư sinh lời ngắn hạn trong vòng 1 năm.", "Marketable securities", "PRO-A2", 91, [("余剰資金で取得した国債を有価証券として流動資産に計上する。", "Trái phiếu chính phủ mua bằng tiền nhàn rỗi được hạch toán vào tài sản ngắn hạn dưới dạng chứng khoán.", "Government bonds acquired with surplus funds are recorded under current assets as securities.")], [], ["有価証券を売却する", "時価評価"], ["投資有価証券", "有価証券売却益"]),
    ("棚卸資産", "たなおろししさん", "tanaoroshishisan", "hàng tồn kho", "Toàn bộ tài sản doanh nghiệp đang nắm giữ để bán, đang trong quá trình chế tạo hoặc nguyên vật liệu sản xuất.", "Inventories", "PRO-A2", 94, [("期末棚卸資産の金額は売上原価の算定に直接影響します。", "Giá trị hàng tồn kho cuối kỳ ảnh hưởng trực tiếp đến việc tính giá vốn hàng bán.", "The year-end inventory amount directly affects the calculation of cost of sales.")], [], ["実地棚卸", "棚卸資産評価損"], ["商品", "製品", "仕掛品"]),
    ("商品", "しょうひん", "shouhin", "hàng hóa", "Các mặt hàng được doanh nghiệp mua từ bên ngoài về với mục đích bán lại nguyên trạng mà không qua gia công chế tạo.", "Merchandise", "PRO-A1", 96, [("仕入れた商品は倉庫に保管し、受注に応じて出荷します。", "Hàng hóa mua về được lưu giữ tại kho và xuất hàng theo đơn đặt.", "Purchased merchandise is stored in the warehouse and shipped according to orders.")], [], ["商品仕入高", "商品売買益"], ["製品", "棚卸資産"]),
    ("製品", "せいひん", "seihin", "thành phẩm", "Sản phẩm do chính doanh nghiệp tự sản xuất hoàn chỉnh và sẵn sàng để bán cho khách hàng.", "Finished goods", "PRO-A1", 95, [("完成した製品を検品後、製品倉庫へ入庫した。", "Sau khi kiểm tra chất lượng, thành phẩm được nhập vào kho thành phẩm.", "After inspecting completed finished goods, we stored them in the finished goods warehouse.")], [], ["製品在庫", "製品保証"], ["商品", "半製品", "仕掛品"]),
    ("半製品", "はんせいひん", "hanseihin", "bán thành phẩm", "Sản phẩm đã hoàn thành một số công đoạn chế tạo nhất định, có thể đem bán riêng hoặc tiếp tục chế tạo tiếp.", "Semi-finished goods", "PRO-A2", 89, [("半製品の状態で一部の部品を外部の取引先へ納品する。", "Giao một phần linh kiện cho đối tác bên ngoài dưới dạng bán thành phẩm.", "Deliver some components to external partners as semi-finished goods.")], [], ["半製品在庫", "工程管理"], ["仕掛品", "製品"]),
    ("原材料", "げんざいりょう", "genzairyou", "nguyên vật liệu", "Các loại vật liệu thô mua về để đưa vào quy trình sản xuất chế tạo sản phẩm.", "Raw materials", "PRO-A1", 95, [("原材料の仕入価格の上昇が製造原価を押し上げている。", "Giá mua nguyên vật liệu tăng cao đang đẩy giá thành sản xuất lên.", "Rising purchase prices of raw materials are pushing up manufacturing costs.")], [], ["原材料費", "原材料仕入"], ["仕掛品", "製品"]),
    ("仕掛品", "しかかりひん", "shikakarihin", "sản phẩm dở dang", "Sản phẩm đang trong quá trình gia công sản xuất trên dây chuyền, chưa hoàn thành trọn vẹn tại thời điểm tính giá thành.", "Work in process", "PRO-A2", 91, [("月末の製造工程に残っている未完成品を仕掛品として評価する。", "Định giá các sản phẩm chưa hoàn tất còn trên dây chuyền cuối tháng là sản phẩm dở dang.", "Value incomplete items remaining on the production line at month-end as work in process.")], [], ["仕掛品勘定", "工程別原価計算"], ["原材料", "製品"]),
    ("貯蔵品", "ちょぞうひん", "chozouhin", "vật tư phụ tùng tồn kho", "Các loại vật tư văn phòng chưa sử dụng, tem thư, phiếu quà tặng, phụ tùng thay thế được lưu kho.", "Supplies", "PRO-A2", 88, [("決算時に未使用の切手や印紙を通信費から貯蔵品へ振り替えた。", "Tại thời điểm quyết toán, chuyển tem và tem lệ phí chưa dùng từ chi phí bưu chính sang tài khoản vật tư tồn kho.", "Transferred unused stamps and revenue stamps from postage to supplies at closing.")], [], ["貯蔵品勘定", "未使用分振替"], ["消耗品費"]),
    ("前払費用", "まえばらいひよう", "maebaraihiyou", "chi phí trả trước", "Khoản tiền đã thanh toán trước cho dịch vụ sẽ được hưởng liên tục trong các kỳ kế toán tương lai.", "Prepaid expenses", "PRO-A2", 92, [("1年分の賃料を一括払いしたため、未経過分を前払費用として計上する。", "Vì đã trả tiền thuê 1 năm một lần, nên trích phần thời gian chưa trôi qua vào chi phí trả trước.", "Because one year of rent was paid upfront, the unexpired portion is recognized as prepaid expenses.")], [], ["前払費用計上", "経過勘定"], ["未払費用", "前受収益"]),
    ("前渡金", "まえわたしきん", "maewatashikin", "tiền ứng trước cho người bán", "Số tiền doanh nghiệp đặt cọc hoặc trả trước cho nhà cung cấp trước khi nhận hàng hóa hoặc dịch vụ.", "Advances paid", "PRO-A1", 93, [("設備の発注時に契約金の一部を前渡金として支払った。", "Khi đặt mua máy móc, chúng tôi đã trả trước một phần tiền cọc hợp đồng.", "Paid part of the contract price as advances paid when ordering equipment.")], [], ["前渡金を支払う", "手付金"], ["前受金", "買掛金"]),
    ("未収入金", "みしゅうにゅうきん", "mishuunyuukin", "khoản phải thu khác", "Tiền có quyền thu phát sinh từ các giao dịch bán tài sản không thuộc hàng hóa kinh doanh chính.", "Accounts receivable - other", "PRO-A1", 93, [("使わなくなった社用車を売却し、代金未回収分を未収入金とした。", "Bán xe công ty không dùng nữa và ghi số tiền chưa thu vào khoản phải thu khác.", "Sold an unused company car and recorded the uncollected balance as accounts receivable - other.")], [], ["未収入金を回収する", "資産売却代金"], ["未払金", "売掛金"]),
    ("短期貸付金", "たんきかしつけきん", "tankikashitsukekin", "cho vay ngắn hạn", "Khoản tiền doanh nghiệp cho công ty con, đối tác hoặc nhân viên vay với kỳ hạn thu hồi dưới 1 năm.", "Short-term loans receivable", "PRO-A2", 89, [("子会社の一時的な資金不足を補うため、短期貸付金を実行した。", "Cung cấp khoản cho vay ngắn hạn để bù đắp thiếu hụt dòng tiền tạm thời của công ty con.", "Executed short-term loans to cover the subsidiary's temporary cash shortage.")], [], ["短期貸付金利息", "貸付金残高"], ["長期貸付金", "受取利息"]),
    ("貸倒引当金", "かしだおれひきあてきん", "kashidaorehikiatekin", "dự phòng nợ phải thu khó đòi", "Khoản trích trước vào chi phí để bù đắp các khoản công nợ có khả năng bị thất thoát không thu hồi được.", "Allowance for doubtful accounts", "PRO-A2", 94, [("期末の売掛金残高に対して過去の実績率に基づき貸倒引当金を計上する。", "Trích lập dự phòng nợ khó đòi trên số dư nợ phải thu cuối kỳ dựa theo tỷ lệ tổn thất quá khứ.", "Recognize an allowance for doubtful accounts on year-end receivables based on historical default rates.")], [], ["引当金繰入", "個別評価引当金"], ["貸倒損失", "売掛金"]),
    ("立替金", "たてかえきん", "tatekaekin", "khoản chi hộ / ứng tiền trước", "Khoản tiền doanh nghiệp tạm thời chi trả hộ cho đối tác, khách hàng hoặc nhân viên và sẽ được thu lại sau.", "Advances paid / Claims for reimbursement", "PRO-A1", 92, [("出張者の旅費交通費を会社が一時的に立替金として処理した。", "Công ty tạm thời xử lý chi phí đi lại của người đi công tác dưới dạng tiền ứng trước chi hộ.", "The company temporarily processed the business traveler's transportation costs as advances paid.")], [], ["立替金を精算する", "立替払い"], ["預り金", "仮払金"]),
    ("仮払金", "かりばらいきん", "karibaraikin", "khoản tạm ứng", "Số tiền đã xuất quỹ đưa cho nhân viên nhưng chưa xác định được nội dung chi phí cụ thể hoặc số tiền chính xác.", "Suspense payments", "PRO-A1", 93, [("海外出張に行く営業担当者に概算で仮払金50万円を支給した。", "Cấp tạm ứng ước tính 50 vạn yên cho nhân viên kinh doanh đi công tác nước ngoài.", "Disbursed suspense payments of 500,000 yen as an estimate to the sales rep traveling abroad.")], [], ["仮払金を精算する", "仮払金残高"], ["仮受金", "立替金"]),
    ("未収収益", "みしゅうしゅうえき", "mishuushuueki", "doanh thu dồn tích / lãi dự thu", "Khoản doanh thu đã phát sinh từ dịch vụ cung cấp liên tục trong kỳ nhưng chưa đến kỳ hạn thu tiền theo hợp đồng.", "Accrued income", "PRO-A2", 89, [("定期預金の未収利息を決算日に未収収益として計上した。", "Hạch toán tiền lãi chưa thu của khoản tiết kiệm định kỳ vào doanh thu dồn tích tại ngày quyết toán.", "Recorded accrued interest on time deposits as accrued income on the closing date.")], [], ["未収利息", "経過勘定計上"], ["前受収益", "未払費用"]),
    ("繰延税金資産", "くりのべぜいきんしさん", "kurinobezeikinshisan", "tài sản thuế thu nhập hoãn lại", "Khoản chênh lệch thuế phát sinh do chi phí đã ghi nhận trên kế toán nhưng chưa được trừ theo luật thuế trong kỳ này.", "Deferred tax assets", "PRO-A3", 90, [("将来減算一時差異に基づき、回収可能性があると判断した繰延税金資産を計上する。", "Căn cứ vào chênh lệch tạm thời được khấu trừ trong tương lai, ghi nhận tài sản thuế hoãn lại có khả năng thu hồi.", "Recognize deferred tax assets judged recoverable based on deductible temporary differences.")], [], ["回収可能性の検討", "一時差異"], ["繰延税金負債", "税効果会計"]),
    ("流動資産合計", "りゅうどうしさんごうけい", "ryuudoushishangoukei", "tổng tài sản ngắn hạn", "Tổng giá trị của tất cả các tài sản bằng tiền, tài sản có thể chuyển đổi thành tiền hoặc tiêu thụ trong vòng 1 năm.", "Total current assets", "PRO-A1", 94, [("流動比率を計算するために流動資産合計と流動負債合計を比較する。", "So sánh tổng tài sản ngắn hạn với tổng nợ ngắn hạn để tính tỷ số thanh toán hiện hành.", "Compare total current assets with total current liabilities to calculate the current ratio.")], [], ["流動比率", "短期安全性"], ["流動負債合計", "固定資産合計"]),

    # Non-Current Assets (27-50)
    ("有形固定資産", "ゆうけいこていしさん", "yuukeikoteishisan", "tài sản cố định hữu hình", "Tài sản có hình thái vật chất sử dụng cho hoạt động kinh doanh lâu dài trên 1 năm.", "Property, plant and equipment", "PRO-A2", 94, [("生産能力増強のために工場建屋を有形固定資産として取得した。", "Đã mua thêm nhà xưởng làm tài sản cố định hữu hình để nâng cao năng lực sản xuất.", "Acquired plant buildings as property, plant and equipment to augment production capacity.")], [], ["有形固定資産の取得", "減価償却"], ["無形固定資産", "減損損失"]),
    ("建物", "たてもの", "tatemono", "nhà cửa / công trình kiến trúc", "Các công trình nhà xưởng, văn phòng, nhà kho thuộc quyền sở hữu của doanh nghiệp.", "Buildings", "PRO-A1", 95, [("本社ビル建物の減価償却費を定額法で毎年計上しています。", "Trích khấu hao nhà tòa nhà trụ sở chính hàng năm theo phương pháp đường thẳng.", "Depreciation expense for the headquarters building is recorded annually using the straight-line method.")], [], ["建物勘定", "付属設備"], ["土地", "減価償却累計額"]),
    ("構築物", "こうちくぶつ", "kouchikubutsu", "vật kiến trúc", "Các công trình xây dựng gắn liền với đất nhưng không phải là nhà ở (như cầu cống, đường ray, hàng rào, ống khói, bãi đỗ xe).", "Structures", "PRO-A2", 88, [("工場敷地内の舗装道路やフェンスは構築物として分類されます。", "Đường nhựa nội bộ và hàng rào trong khuôn viên nhà xưởng được phân loại là vật kiến trúc.", "Paved roads and fences on factory premises are classified as structures.")], [], ["構築物の償却", "屋外設備"], ["建物", "土地"]),
    ("機械及び装置", "きかいおよびそうち", "kikaioyobisouchi", "máy móc và thiết bị sản xuất", "Hệ thống máy móc, dây chuyền kỹ thuật dùng trực tiếp trong sản xuất hoặc cung cấp dịch vụ.", "Machinery and equipment", "PRO-A1", 95, [("新鋭の自動化設備を導入し、機械及び装置として固定資産台帳に登録した。", "Đưa vào vận hành dây chuyền tự động hóa mới và đăng ký vào sổ tài sản cố định dưới tên máy móc thiết bị.", "Introduced state-of-the-art automated equipment and registered it as machinery and equipment in the fixed asset ledger.")], [], ["設備投資", "稼働率"], ["工具器具備品", "減価償却"]),
    ("車両運搬具", "しゃりょううんぱんぐ", "sharyouunpangu", "phương tiện vận tải", "Xe ô tô, xe tải, xe nâng hàng được doanh nghiệp sở hữu để phục vụ kinh doanh hoặc chở hàng.", "Vehicles", "PRO-A1", 94, [("営業活動用に購入したハイブリッド車を車両運搬具に計上した。", "Ghi nhận xe hybrid mua phục vụ hoạt động kinh doanh vào tài khoản phương tiện vận tải.", "Recorded hybrid cars purchased for sales activities under vehicles.")], [], ["社用車", "車両維持費"], ["工具器具備品"]),
    ("工具器具備品", "こうぐきぐびひん", "kougukigubihin", "công cụ, dụng cụ và thiết bị văn phòng", "Các thiết bị máy tính, bàn ghế, tủ hồ sơ, máy móc chuyên dụng nhỏ có giá trị trên mức quy định tài sản.", "Tools, furniture and fixtures", "PRO-A1", 94, [("オフィス移転に伴い一括購入したデスクやサーバーは工具器具備品とする。", "Bàn ghế và máy chủ mua đồng loạt khi chuyển văn phòng được tính vào công cụ dụng cụ và thiết bị.", "Desks and servers purchased in bulk during office relocation are classified as tools, furniture and fixtures.")], [], ["備品管理台帳", "耐用年数"], ["消耗品費", "機械及び装置"]),
    ("土地", "とち", "tochi", "quyền sử dụng đất / đất đai", "Diện tích đất đai thuộc quyền sở hữu của doanh nghiệp, là tài sản cố định không bị hao mòn theo thời gian nên không trích khấu hao.", "Land", "PRO-A1", 95, [("工場用地として取得した土地は減価償却の対象外となります。", "Đất đai mua làm mặt bằng nhà xưởng không thuộc đối tượng trích khấu hao.", "Land acquired for factory sites is not subject to depreciation.")], [], ["土地の取得", "固定資産税評価額"], ["建物", "減損会計"]),
    ("建設仮勘定", "けんせつかりかんじょう", "kensetsukarikanjou", "chi phí xây dựng cơ bản dở dang", "Khoản chi phí đang tích lũy trong quá trình thi công xây dựng công trình hoặc chế tạo máy móc trước khi hoàn tất bàn giao sử dụng.", "Construction in progress", "PRO-A2", 91, [("新工場が完成するまでの支出はすべて建設仮勘定に集約する。", "Toàn bộ chi phí cho đến khi nhà xưởng mới hoàn thành đều được tập hợp vào chi phí xây dựng cơ bản dở dang.", "All expenditures until the new plant is completed are consolidated into construction in progress.")], [], ["本勘定振替", "設備投資進捗"], ["有形固定資産", "建物"]),
    ("減価償却累計額", "げんかしょうきゃくるいけいがく", "genkashoukyakurruikeigaku", "hao mòn lũy kế tài sản cố định", "Tổng số tiền khấu hao đã trích từ khi đưa tài sản vào sử dụng đến thời điểm hiện tại, ghi nhận điều chỉnh giảm giá trị tài sản.", "Accumulated depreciation", "PRO-A2", 93, [("建物の取得原価から減価償却累計額を控除して帳簿価額を求める。", "Lấy nguyên giá nhà cửa trừ đi hao mòn lũy kế để ra giá trị ghi sổ còn lại.", "Deduct accumulated depreciation from the building's acquisition cost to obtain book value.")], [], ["間接控除", "帳簿価額"], ["減価償却費", "有形固定資産"]),
    ("無形固定資産", "むけいこていしさん", "mukeikoteishisan", "tài sản cố định vô hình", "Tài sản dài hạn không có hình thái vật chất nhưng mang lại quyền lợi kinh tế pháp lý (như bằng sáng chế, phần mềm).", "Intangible assets", "PRO-A2", 93, [("無形固定資産は定額法によって耐用年数内で償却されます。", "Tài sản cố định vô hình được phân bổ khấu hao theo phương pháp đường thẳng trong thời gian sử dụng hữu ích.", "Intangible assets are amortized over their useful life using the straight-line method.")], [], ["無形資産の償却", "知的財産"], ["有形固定資産", "のれん", "ソフトウェア"]),
    ("のれん", "のれん", "noren", "lợi thế thương mại (goodwill)", "Phần chênh lệch trả cao hơn giá trị tài sản ròng khi mua lại sáp nhập một doanh nghiệp khác.", "Goodwill", "PRO-A2", 92, [("買収時に生じたのれんは20年以内の均等償却が日本基準で求められます。", "Chuẩn mực Nhật Bản yêu cầu phân bổ đều lợi thế thương mại phát sinh khi mua lại công ty trong vòng 20 năm.", "Under Japanese GAAP, goodwill arising from acquisitions must be amortized evenly within 20 years.")], [], ["のれん償却費", "のれん減損"], ["企業結合", "無形固定資産"]),
    ("特許権", "とっきょけん", "tokkyoken", "quyền sở hữu bằng sáng chế", "Quyền độc quyền khai thác sáng chế công nghệ đã được cơ quan sở hữu trí tuệ cấp bằng bảo hộ.", "Patent right", "PRO-A2", 90, [("自社開発した新技術の特許権を無形固定資産に計上した。", "Hạch toán quyền sáng chế công nghệ mới tự phát triển vào tài sản cố định vô hình.", "Recorded patent rights for internally developed new technology as intangible assets.")], [], ["特許権の取得", "特許料収入"], ["無形固定資産", "知的財産権"]),
    ("ソフトウェア", "そふとうぇあ", "sofutowea", "phần mềm máy tính", "Các phần mềm nghiệp vụ mua ngoài hoặc tự phát triển phục vụ hoạt động nội bộ công ty được vốn hóa làm tài sản.", "Software", "PRO-A1", 95, [("基幹業務システム用のソフトウェア開発費を資産計上する。", "Vốn hóa chi phí phát triển phần mềm hệ thống ERP thành tài sản.", "Capitalize development costs of core business software as an asset.")], [], ["自社利用ソフトウェア", "市場販売目的ソフトウェア"], ["無形固定資産", "減価償却費"]),
    ("借地権", "しゃくちけん", "shakuchiken", "quyền thuê đất dài hạn", "Quyền sử dụng đất của người khác để xây dựng công trình dựa trên hợp đồng thuê đất dài hạn.", "Right of leasehold", "PRO-A2", 87, [("借地権の対価として地主に支払った権利金を無形固定資産とする。", "Tiền quyền lợi thuê trả cho chủ đất để có quyền thuê đất được ghi nhận là tài sản cố định vô hình.", "The key money paid to landlords as consideration for leasehold rights is treated as intangible assets.")], [], ["借地権設定", "底地"], ["土地", "無形固定資産"]),
    ("投資有価証券", "とうしゆうかしょうけん", "toushiyuukashouken", "chứng khoán đầu tư dài hạn", "Cổ phiếu, trái phiếu được doanh nghiệp nắm giữ với mục đích duy trì quan hệ kinh doanh lâu dài hoặc đầu tư dài hạn.", "Investment securities", "PRO-A2", 92, [("業務提携先との関係強化のために保有する株式は投資有価証券に属する。", "Cổ phiếu nắm giữ để thắt chặt quan hệ với đối tác liên kết thuộc danh mục chứng khoán đầu tư.", "Shares held to strengthen relationships with business alliance partners belong to investment securities.")], [], ["政策保有株式", "その他有価証券評価差額金"], ["有価証券", "関係会社株式"]),
    ("関係会社株式", "かんけいがいしゃかぶしき", "kankeigaishakabushiki", "cổ phiếu công ty liên kết / công ty con", "Cổ phiếu do doanh nghiệp nắm giữ tại các công ty con hoặc công ty liên kết nhằm mục đích chi phối quản trị.", "Stocks of subsidiaries and associates", "PRO-A2", 91, [("完全子会社の設立に伴い出資した金額は関係会社株式となる。", "Số tiền góp vốn thành lập công ty con 100% vốn trở thành khoản mục cổ phiếu công ty liên kết.", "Capital invested upon establishing a wholly owned subsidiary becomes stocks of subsidiaries.")], [], ["持分比率", "支配力獲得"], ["投資有価証券", "連結財務諸表"]),
    ("敷金", "しききん", "shikikin", "tiền đặt cọc thuê nhà", "Số tiền doanh nghiệp đặt cọc cho chủ nhà khi ký hợp đồng thuê văn phòng, cửa hàng và sẽ được hoàn lại khi kết thúc hợp đồng.", "Leasehold deposits", "PRO-A1", 94, [("賃貸オフィスの敷金は契約終了時に返還されるため投資その他の資産に計上する。", "Tiền đặt cọc văn phòng thuê sẽ được hoàn trả khi hết hợp đồng nên hạch toán vào mục đầu tư và tài sản khác.", "Office leasehold deposits are recorded under investments and other assets since they are refundable at contract termination.")], [], ["敷金返還", "敷引"], ["保証金", "前払費用"]),
    ("保証金", "ほしょうきん", "hoshoukin", "tiền ký quỹ / tiền bảo đảm", "Khoản tiền ký quỹ bảo đảm thực hiện hợp đồng giao dịch thương mại hoặc đấu thầu.", "Security deposits / Guarantee deposits", "PRO-A1", 93, [("取引開始に伴い代理店契約の保証金を差し入れた。", "Đã nộp tiền ký quỹ bảo đảm theo hợp đồng đại lý khi bắt đầu giao dịch.", "Deposited guarantee money for the agency agreement upon commencing business.")], [], ["差入保証金", "保証金の預け入れ"], ["敷金", "投資その他の資産"]),
    ("長期前払費用", "ちょうきまえばらいひよう", "choukkimaebaraihiyou", "chi phí trả trước dài hạn", "Các khoản chi phí đã trả trước có thời gian phân bổ vào chi phí trên 1 năm kể từ ngày kết thúc niên độ.", "Long-term prepaid expenses", "PRO-A2", 89, [("5年契約の保証料を一括で支払ったため長期前払費用に振り替えた。", "Do thanh toán phí bảo lãnh hợp đồng 5 năm một lần nên đã chuyển sang chi phí trả trước dài hạn.", "Transferred to long-term prepaid expenses because the five-year guarantee fee was paid in lump sum.")], [], ["長期前払費用償却", "1年基準"], ["前払費用", "経過勘定"]),
    ("創立費", "そうりつひ", "souritsuhi", "chi phí thành lập doanh nghiệp", "Các chi phí phát sinh trước khi công ty được đăng ký thành lập (tiền thù lao luật sư, phí công chứng điều lệ, lệ phí đăng ký).", "Organization expenses", "PRO-A2", 88, [("会社設立にかかった登記免許税や定款認証費用を創立費として繰延資産にした。", "Thuế trước bạ và phí chứng thực điều lệ phát sinh khi thành lập công ty được hạch toán là chi phí thành lập.", "Recorded registration taxes and notary fees for incorporation as organization expenses under deferred assets.")], [], ["繰延資産", "創立費償却"], ["開業費", "資本金"]),
    ("開業費", "かいぎょうひ", "kaigyouhi", "chi phí chuẩn bị hoạt động kinh doanh", "Chi phí phát sinh từ thời điểm công ty thành lập đến khi chính thức bắt đầu hoạt động kinh doanh thương mại.", "Pre-operating expenses", "PRO-A2", 88, [("店舗オープンまでの広告宣伝やスタッフ研修費用を開業費に計上する。", "Chi phí quảng cáo và đào tạo nhân viên trước ngày khai trương cửa hàng được ghi nhận vào chi phí chuẩn bị hoạt động.", "Expensed advertising and staff training costs prior to store opening as pre-operating expenses.")], [], ["開業費の償却", "任意償却"], ["創立費", "繰延資産"]),
    ("固定資産合計", "こていしさんごうけい", "koteishishangoukei", "tổng tài sản dài hạn", "Tổng giá trị gộp của tài sản cố định hữu hình, tài sản vô hình và các khoản đầu tư dài hạn khác.", "Total non-current assets", "PRO-A1", 94, [("貸借対照表において流動資産合計と固定資産合計を足したものが総資産となります。", "Trên bảng cân đối kế toán, tổng tài sản ngắn hạn cộng tổng tài sản dài hạn chính là tổng tài sản.", "On the balance sheet, adding total current assets and total non-current assets yields total assets.")], [], ["固定比率", "資産構成"], ["流動資産合計", "資産合計"]),
    ("資産合計", "しさんごうけい", "shishangoukei", "tổng tài sản", "Tổng toàn bộ giá trị tài sản mà doanh nghiệp sở hữu, bằng tổng nợ phải trả cộng vốn chủ sở hữu.", "Total assets", "PRO-A1", 98, [("今期の総資産利益率（ROA）は前年を上回る結果となった。", "Tỷ suất sinh lời trên tổng tài sản (ROA) kỳ này đạt kết quả vượt năm trước.", "Return on total assets (ROA) for this period exceeded the previous year's result.")], [], ["総資産", "総資産回転率", "ROA"], ["負債純資産合計", "貸借バランス"]),
]

print(f"[+] Defined {len(RAW_ACCOUNTING_200)} detailed template entries. Generating remaining programmatic entries to reach 200 ...")
