#!/usr/bin/env python3
"""
scripts/pilot_builder/make_accounting.py
Builds the 200 authoritative canonical accounting entries.
"""

import json
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent.parent
OUT_FILE = BASE_DIR / "scripts" / "pilot_builder" / "accounting.py"

# We select the top 200 essential accounting concepts spanning:
# Financial Statements, Current Assets, Non-Current Assets, Current Liabilities,
# Non-Current Liabilities, Equity/Capital, Sales/Revenue, Cost of Sales, SG&A Expenses,
# Non-Operating & Extraordinary Items, Bookkeeping Mechanics, Auditing & Standards.

ACCOUNTING_DEFINITIONS = [
    # --- 1. Financial Statements & Reporting (1-15) ---
    ("貸借対照表", "たいしゃくたいしょうひょう", "bảng cân đối kế toán", "Báo cáo tài chính phản ánh tổng quát toàn bộ tài sản, nợ phải trả và vốn chủ sở hữu tại thời điểm khóa sổ kế toán.", "Balance sheet", "PRO-A1", 99, "1f_AccountList.xlsx:BalanceSheet", ["B/S"], [], ["損益計算書", "資産", "負債"]),
    ("損益計算書", "そんえきけいさんしょ", "báo cáo kết quả hoạt động kinh doanh", "Báo cáo tài chính tổng hợp toàn bộ doanh thu, chi phí và lợi nhuận hoặc lỗ thuần phát sinh trong kỳ kế toán.", "Income statement", "PRO-A1", 99, "1f_AccountList.xlsx:StatementOfIncome", ["P/L"], [], ["貸借対照表", "売上高", "営業利益"]),
    ("キャッシュ・フロー計算書", "きゃっしゅふろーけいさんしょ", "báo cáo lưu chuyển tiền tệ", "Báo cáo tài chính thể hiện dòng tiền thực tế vào và ra trong kỳ từ hoạt động kinh doanh, đầu tư và tài chính.", "Cash flow statement", "PRO-A2", 95, "1f_AccountList.xlsx:StatementOfCashFlows", ["C/F"], [], ["営業活動によるキャッシュ・フロー"]),
    ("株主資本等変動計算書", "かぶぬししほんとうへんどうけいさんしょ", "báo cáo biến động vốn chủ sở hữu", "Báo cáo tài chính chi tiết biến động của từng khoản mục vốn chủ sở hữu và thặng dư trong kỳ.", "Statement of changes in equity", "PRO-A3", 88, "1f_AccountList.xlsx:StatementOfChangesInEquity", ["S/S"], [], ["株主資本", "利益剰余金"]),
    ("附属明細表", "ふぞくめいさいひょう", "bảng thuyết minh chi tiết kèm theo báo cáo tài chính", "Bảng biểu chi tiết kèm theo giải trình về tài sản cố định, nợ vay, vốn góp theo Luật Doanh nghiệp Nhật Bản.", "Supplementary schedules", "PRO-A3", 85, "1f_AccountList.xlsx:SupplementarySchedules", [], [], ["有価証券報告書"]),
    ("連結財務諸表", "れんけつざいむしょひょう", "báo cáo tài chính hợp nhất", "Báo cáo tài chính tổng hợp phản ánh tình hình tài chính của toàn bộ tập đoàn gồm công ty mẹ và các công ty con.", "Consolidated financial statements", "PRO-A2", 94, "1f_AccountList.xlsx:ConsolidatedFinancialStatements", [], [], ["個別財務諸表", "連結子会社"]),
    ("個別財務諸表", "こべつざいむしょひょう", "báo cáo tài chính riêng lẻ", "Báo cáo tài chính phản ánh độc lập tình hình tài chính và kết quả của riêng công ty mẹ.", "Non-consolidated financial statements", "PRO-A2", 90, "1f_AccountList.xlsx:NonConsolidatedFinancialStatements", [], [], ["連結財務諸表"]),
    ("四半期財務諸表", "しはんきざいむしょひょう", "báo cáo tài chính quý", "Báo cáo tài chính định kỳ 3 tháng do các công ty niêm yết lập theo Luật Giao dịch Công cụ Tài chính.", "Quarterly financial statements", "PRO-A2", 91, "1f_AccountList.xlsx:QuarterlyFinancialStatements", [], [], ["四半期レビュー", "有価証券報告書"]),
    ("決算短信", "けっさんたんしん", "bản tóm tắt kết quả kinh doanh", "Bản công bố thông tin tài chính nhanh nộp cho Sở giao dịch chứng khoán ngay sau khi kết thúc kỳ kế toán.", "Earnings report / Financial summary", "PRO-A2", 93, "jicpa_glossary", ["短信"], [], ["適時開示", "有価証券報告書"]),
    ("有価証券報告書", "ゆうかしょうけんほうこくしょ", "báo cáo chứng khoán hàng năm (Yukaho)", "Báo cáo thường niên chi tiết bắt buộc nộp lên cơ quan tài chính qua EDINET theo Luật Giao dịch Tài chính.", "Annual securities report", "PRO-A2", 94, "fsa_edinet_2026", ["有報"], [], ["EDINET", "金融商品取引法"]),
    ("総資産", "そうしさん", "tổng tài sản", "Tổng giá trị của tất cả tài sản ngắn hạn và tài sản dài hạn thuộc quyền sở hữu của doanh nghiệp.", "Total assets", "PRO-A1", 98, "1f_AccountList.xlsx:TotalAssets", ["資産合計"], [], ["総資本", "純資産"]),
    ("総負債", "そうふさい", "tổng nợ phải trả", "Tổng toàn bộ các nghĩa vụ nợ ngắn hạn và nợ dài hạn mà doanh nghiệp phải thanh toán.", "Total liabilities", "PRO-A1", 96, "1f_AccountList.xlsx:TotalLiabilities", ["負債合計"], [], ["総資産", "純資産"]),
    ("純資産", "じゅんしさん", "tài sản thuần / vốn chủ sở hữu", "Chênh lệch giữa tổng tài sản và tổng nợ phải trả, đại diện cho phần giá trị thực sự thuộc về các cổ đông.", "Net assets", "PRO-A1", 98, "1f_AccountList.xlsx:NetAssets", ["自己資本"], [], ["総資産", "負債"]),
    ("自己資本比率", "じこしほんひりつ", "tỷ lệ vốn chủ sở hữu trên tổng tài sản", "Tỷ lệ phần trăm giữa vốn chủ sở hữu so với tổng tài sản, là thước đo an toàn tài chính quan trọng hàng đầu.", "Equity ratio", "PRO-A2", 95, "jicpa_glossary", [], [], ["純資産", "財務健全性"]),
    ("流動比率", "りゅうどうひりつ", "tỷ số thanh toán hiện hành", "Tỷ lệ giữa tài sản ngắn hạn và nợ ngắn hạn, đánh giá khả năng thanh toán các khoản nợ đến hạn trong vòng 1 năm.", "Current ratio", "PRO-A2", 94, "jicpa_glossary", [], [], ["流動資産", "流動負債"]),

    # --- 2. Current Assets (16-45) ---
    ("現金及び預金", "げんきんおよびよきん", "tiền mặt và tiền gửi ngân hàng", "Khoản mục phản ánh tổng tiền mặt tại quỹ và các tài khoản tiền gửi tại các tổ chức tín dụng.", "Cash and deposits", "PRO-A1", 98, "1f_AccountList.xlsx:CashAndDeposits", ["現預金"], [], ["当座預金", "普通預金"]),
    ("小口現金", "こぐちげんきん", "quỹ tiền mặt nhỏ / tiền tiêu vặt văn phòng", "Khoản tiền mặt nhỏ được thủ quỹ giao cho các phòng ban giữ để chi trả các khoản chi tiêu lặt vặt hàng ngày.", "Petty cash", "PRO-A1", 95, "bookkeeping_foundation", [], [], ["定額資金前渡法", "現金出納帳"]),
    ("当座預金", "とうざよきん", "tiền gửi vãng lai / tiền gửi thanh toán", "Tài khoản tiền gửi ngân hàng không kỳ hạn, không có lãi suất, dùng để phát hành séc và thanh toán thương phiếu.", "Current account / Checking account", "PRO-A1", 96, "1f_AccountList.xlsx:CurrentDeposits", [], [], ["普通預金", "小切手", "手形"]),
    ("普通預金", "ふつうよきん", "tiền gửi ngân hàng thông thường", "Tài khoản tiền gửi thanh toán linh hoạt hàng ngày của doanh nghiệp, có phát sinh lãi tiền gửi định kỳ.", "Ordinary deposits / Savings deposits", "PRO-A1", 98, "1f_AccountList.xlsx:OrdinaryDeposits", [], [], ["当座預金", "振込"]),
    ("定期預金", "ていきよきん", "tiền gửi tiết kiệm có kỳ hạn", "Khoản tiền gửi ngân hàng có kỳ hạn cố định, hưởng lãi suất cao hơn và không được rút tự do trước hạn.", "Time deposits", "PRO-A1", 92, "1f_AccountList.xlsx:TimeDeposits", [], [], ["普通預金", "受取利息"]),
    ("売掛金", "うりかけきん", "khoản phải thu khách hàng", "Khoản tiền bán hàng hóa, dịch vụ cho khách hàng theo hình thức thanh toán sau mà doanh nghiệp chưa thu được tiền.", "Accounts receivable - trade", "PRO-A1", 100, "1f_AccountList.xlsx:AccountsReceivableTrade", ["売上債権"], ["買掛金"], ["受取手形", "未収入金", "消込"]),
    ("受取手形", "うけとりてがた", "thương phiếu phải thu", "Kỳ phiếu hoặc hối phiếu do người mua ký phát hoặc chấp nhận cam kết trả tiền khi đến ngày đáo hạn.", "Notes receivable - trade", "PRO-A2", 94, "1f_AccountList.xlsx:NotesReceivableTrade", [], ["支払手形"], ["手形割引", "売掛金"]),
    ("電子記録債権", "でんしきろくさいけん", "chứng từ nợ điện tử phải thu (Densai)", "Quyền đòi tiền được số hóa và ghi nhận trên hệ thống đăng ký điện tử của hiệp hội ngân hàng Nhật Bản.", "Electronically recorded monetary claims", "PRO-A2", 94, "1f_AccountList.xlsx:ElectronicallyRecordedMonetaryClaimsOperating", ["でんさい"], ["電子記録債務"], ["受取手形", "売掛金"]),
    ("売上債権", "うりあげさいけん", "nợ phải thu thương mại", "Thuật ngữ tổng hợp chỉ toàn bộ các khoản phải thu thương mại phát sinh trực tiếp từ hoạt động bán hàng.", "Trade receivables", "PRO-A2", 95, "1f_AccountList.xlsx:NotesAndAccountsReceivableTrade", [], ["仕入債務"], ["売掛金", "受取手形"]),
    ("有価証券", "ゆうかしょうけん", "chứng khoán ngắn hạn", "Các loại cổ phiếu niêm yết, trái phiếu doanh nghiệp mua với mục đích kinh doanh lướt sóng hoặc dưới 1 năm.", "Securities", "PRO-A2", 92, "1f_AccountList.xlsx:Securities", [], [], ["投資有価証券", "時価評価"]),
    ("棚卸資産", "たなおろししさん", "hàng tồn kho", "Toàn bộ tài sản doanh nghiệp đang nắm giữ để bán, đang trong quá trình chế tạo hoặc nguyên vật liệu sản xuất.", "Inventories", "PRO-A2", 95, "1f_AccountList.xlsx:Inventories", ["在庫"], [], ["商品", "製品", "仕掛品", "実地棚卸"]),
    ("商品", "しょうひん", "hàng hóa", "Các mặt hàng được mua về từ bên ngoài với mục đích bán lại nguyên trạng để kiếm lời.", "Merchandise", "PRO-A1", 96, "1f_AccountList.xlsx:Merchandise", [], [], ["仕入高", "製品"]),
    ("製品", "せいひん", "thành phẩm", "Sản phẩm đã được sản xuất gia công hoàn chỉnh tại nhà xưởng của công ty và sẵn sàng đem tiêu thụ.", "Finished goods", "PRO-A1", 95, "1f_AccountList.xlsx:FinishedGoods", [], [], ["商品", "半製品", "仕掛品"]),
    ("半製品", "はんせいひん", "bán thành phẩm", "Sản phẩm đã hoàn tất một số công đoạn quy định, có thể đem bán riêng biệt hoặc tiếp tục gia công tiếp.", "Semi-finished goods", "PRO-A2", 89, "1f_AccountList.xlsx:SemiFinishedGoods", [], [], ["仕掛品", "製品"]),
    ("原材料", "げんざいりょう", "nguyên vật liệu", "Các loại vật liệu thô mua về dùng trực tiếp cho quy trình sản xuất chế tạo thành phẩm.", "Raw materials", "PRO-A1", 95, "1f_AccountList.xlsx:RawMaterials", [], [], ["仕掛品", "材料費"]),
    ("仕掛品", "しかかりひん", "sản phẩm dở dang", "Sản phẩm đang nằm trên dây chuyền sản xuất chế tạo, chưa hoàn tất tại thời điểm tính giá thành.", "Work in process", "PRO-A2", 92, "1f_AccountList.xlsx:WorkInProcess", [], [], ["原材料", "製造原価"]),
    ("貯蔵品", "ちょぞうひん", "vật tư phụ tùng tồn kho", "Vật tư phụ, tem thư, phiếu quà tặng, văn phòng phẩm mua về chưa sử dụng được kiểm kê cuối kỳ.", "Supplies", "PRO-A2", 88, "1f_AccountList.xlsx:Supplies", [], [], ["消耗品費", "通信費"]),
    ("前払費用", "まえばらいひよう", "chi phí trả trước ngắn hạn", "Khoản tiền đã trả trước cho các dịch vụ sẽ được hưởng liên tục trong vòng 1 năm tới (như tiền thuê nhà, bảo hiểm).", "Prepaid expenses", "PRO-A2", 93, "1f_AccountList.xlsx:PrepaidExpenses", [], ["未払費用"], ["経過勘定", "繰延処理"]),
    ("前渡金", "まえわたしきん", "tiền ứng trước cho người bán", "Khoản tiền đặt cọc hoặc trả trước cho nhà cung cấp trước khi nhận hàng hóa dịch vụ.", "Advances paid", "PRO-A1", 93, "1f_AccountList.xlsx:AdvancesPaid", ["前払金"], ["前受金"], ["買掛金", "手付金"]),
    ("未収入金", "みしゅうにゅうきん", "khoản phải thu khác", "Khoản tiền có quyền thu phát sinh từ việc bán các tài sản không phải là hàng hóa kinh doanh chính.", "Accounts receivable - other", "PRO-A1", 93, "1f_AccountList.xlsx:AccountsReceivableOther", [], ["未払金"], ["売掛金", "固定資産売却"]),
    ("短期貸付金", "たんきかしつけきん", "khoản cho vay ngắn hạn", "Khoản tiền cho công ty con, đối tác hoặc nhân viên vay với thời hạn thu hồi vốn trong vòng 1 năm.", "Short-term loans receivable", "PRO-A2", 89, "1f_AccountList.xlsx:ShortTermLoansReceivable", [], ["短期借入金"], ["長期貸付金", "受取利息"]),
    ("貸倒引当金", "かしだおれひきあてきん", "dự phòng nợ phải thu khó đòi", "Khoản trích trước vào chi phí để bù đắp rủi ro các khoản nợ phải thu khách hàng có thể bị mất trắng.", "Allowance for doubtful accounts", "PRO-A2", 95, "1f_AccountList.xlsx:AllowanceForDoubtfulAccounts", [], [], ["貸倒損失", "売掛金", "引当金繰入"]),
    ("立替金", "たてかえきん", "khoản chi hộ / tạm ứng chi", "Khoản tiền doanh nghiệp tạm thời chi trả hộ cho đối tác hoặc nhân viên và sẽ được thanh toán hoàn lại.", "Advances paid / Claims for reimbursement", "PRO-A1", 92, "1f_AccountList.xlsx:AdvancesPaidToOthers", [], [], ["預り金", "経費精算"]),
    ("仮払金", "かりばらいきん", "khoản tạm ứng trước", "Số tiền tạm xuất quỹ cho nhân viên đi công tác khi chưa rõ số tiền chính xác hoặc chứng từ cụ thể.", "Suspense payments", "PRO-A1", 94, "bookkeeping_foundation", [], ["仮受金"], ["旅費交通費", "精算"]),
    ("未収収益", "みしゅうしゅうえき", "doanh thu dồn tích / lãi dự thu", "Khoản doanh thu tương ứng với dịch vụ đã cung cấp trong kỳ nhưng chưa đến kỳ hạn thanh toán.", "Accrued income", "PRO-A2", 89, "1f_AccountList.xlsx:AccruedIncome", [], ["前受収益"], ["経過勘定", "受取利息"]),
    ("繰延税金資産", "くりのべぜいきんしさん", "tài sản thuế thu nhập hoãn lại", "Khoản thuế thu nhập nộp thừa trong kỳ do chênh lệch tạm thời giữa kế toán và luật thuế, sẽ được thu hồi sau.", "Deferred tax assets", "PRO-A3", 91, "1f_AccountList.xlsx:DeferredTaxAssets", [], ["繰延税金負債"], ["税効果会計", "一時差異"]),
    ("未着品", "みちゃくひん", "hàng đang đi đường", "Hàng hóa đã mua và người bán đã gửi vận chuyển nhưng tại ngày khóa sổ kế toán hàng vẫn chưa nhập kho.", "Goods in transit", "PRO-A2", 88, "1f_AccountList.xlsx:GoodsInTransit", [], [], ["棚卸資産", "貨物引換証"]),
    ("受取配当金", "うけとりはいとうきん", "cổ tức được chia", "Khoản cổ tức mà doanh nghiệp nhận được từ việc đầu tư nắm giữ cổ phiếu của các công ty khác.", "Dividends income", "PRO-A2", 92, "1f_AccountList.xlsx:DividendIncome", [], [], ["営業外収益", "有価証券"]),
    ("受取利息", "うけとりりそく", "tiền lãi nhận được", "Tiền lãi phát sinh từ các khoản tiền gửi ngân hàng, cho vay hoặc trái phiếu mà doanh nghiệp sở hữu.", "Interest income", "PRO-A1", 94, "1f_AccountList.xlsx:InterestIncome", [], ["支払利息"], ["営業外収益", "普通預金"]),
    ("流動資産合計", "りゅうどうしさんごうけい", "tổng tài sản ngắn hạn", "Tổng cộng toàn bộ các tài sản tiền mặt, khoản phải thu, hàng tồn kho chuyển đổi được trong 1 năm.", "Total current assets", "PRO-A1", 95, "1f_AccountList.xlsx:TotalCurrentAssets", [], ["流動負債合計"], ["固定資産合計", "流動比率"]),

    # --- 3. Non-Current Assets (46-75) ---
    ("有形固定資産", "ゆうけいこていしさん", "tài sản cố định hữu hình", "Tài sản có hình thái vật chất sử dụng cho hoạt động kinh doanh lâu dài trên 1 năm.", "Property, plant and equipment", "PRO-A2", 95, "1f_AccountList.xlsx:PropertyPlantAndEquipment", [], ["無形固定資産"], ["減価償却", "固定資産台帳"]),
    ("建物", "たてもの", "nhà cửa / công trình kiến trúc", "Các công trình nhà xưởng, văn phòng, nhà kho thuộc quyền sở hữu của doanh nghiệp.", "Buildings", "PRO-A1", 95, "1f_AccountList.xlsx:Buildings", [], [], ["減価償却費", "付属設備"]),
    ("建物附属設備", "たてものふぞくせつび", "thiết bị gắn liền với nhà cửa", "Hệ thống điều hòa, thang máy, phòng cháy chữa cháy, chiếu sáng được lắp đặt cố định vào tòa nhà.", "Building facilities", "PRO-A2", 90, "1f_AccountList.xlsx:BuildingFacilities", [], [], ["建物", "減価償却"]),
    ("構築物", "こうちくぶつ", "vật kiến trúc", "Các công trình xây dựng gắn liền với đất như bãi đỗ xe, đường nội bộ, hàng rào, cầu cống, bể chứa.", "Structures", "PRO-A2", 89, "1f_AccountList.xlsx:Structures", [], [], ["土地", "有形固定資産"]),
    ("機械及び装置", "きかいおよびそうち", "máy móc và thiết bị sản xuất", "Hệ thống máy móc, dây chuyền kỹ thuật dùng trực tiếp trong sản xuất hoặc cung cấp dịch vụ.", "Machinery and equipment", "PRO-A1", 95, "1f_AccountList.xlsx:MachineryAndEquipment", [], [], ["設備投資", "減価償却"]),
    ("車両運搬具", "しゃりょううんぱんぐ", "phương tiện vận tải", "Xe ô tô, xe tải, xe nâng hàng được doanh nghiệp sở hữu để phục vụ kinh doanh hoặc chở hàng.", "Vehicles", "PRO-A1", 94, "1f_AccountList.xlsx:Vehicles", [], [], ["社用車", "減価償却費"]),
    ("工具器具備品", "こうぐきぐびひん", "công cụ, dụng cụ và thiết bị văn phòng", "Thiết bị máy tính, bàn ghế, tủ hồ sơ, máy móc chuyên dụng nhỏ có giá trị trên mức quy định tài sản.", "Tools, furniture and fixtures", "PRO-A1", 94, "1f_AccountList.xlsx:ToolsFurnitureAndFixtures", [], [], ["備品", "固定資産台帳"]),
    ("土地", "とち", "quyền sử dụng đất / đất đai", "Diện tích đất đai thuộc quyền sở hữu của doanh nghiệp, là tài sản cố định không trích khấu hao.", "Land", "PRO-A1", 95, "1f_AccountList.xlsx:Land", [], [], ["固定資産税", "有形固定資産"]),
    ("建設仮勘定", "けんせつかりかんじょう", "chi phí xây dựng cơ bản dở dang", "Khoản chi phí đang tích lũy trong quá trình thi công xây dựng công trình hoặc chế tạo máy móc trước khi hoàn tất.", "Construction in progress", "PRO-A2", 91, "1f_AccountList.xlsx:ConstructionInProgress", [], [], ["本勘定振替", "設備投資"]),
    ("減価償却累計額", "げんかしょうきゃくるいけいがく", "hao mòn lũy kế tài sản cố định", "Tổng số tiền khấu hao đã trích từ khi đưa tài sản vào sử dụng đến thời điểm hiện tại.", "Accumulated depreciation", "PRO-A2", 94, "1f_AccountList.xlsx:AccumulatedDepreciation", [], [], ["減価償却費", "帳簿価額"]),
    ("無形固定資産", "むけいこていしさん", "tài sản cố định vô hình", "Tài sản dài hạn không có hình thái vật chất nhưng mang lại quyền lợi kinh tế pháp lý.", "Intangible assets", "PRO-A2", 93, "1f_AccountList.xlsx:IntangibleAssets", [], ["有形固定資産"], ["のれん", "ソフトウェア"]),
    ("のれん", "のれん", "lợi thế thương mại (goodwill)", "Phần chênh lệch trả cao hơn giá trị tài sản ròng khi mua lại sáp nhập một doanh nghiệp khác.", "Goodwill", "PRO-A2", 92, "1f_AccountList.xlsx:Goodwill", [], [], ["のれん償却", "M&A"]),
    ("特許権", "とっきょけん", "quyền sở hữu bằng sáng chế", "Quyền độc quyền khai thác sáng chế công nghệ đã được cơ quan sở hữu trí tuệ cấp bằng bảo hộ.", "Patent rights", "PRO-A2", 90, "1f_AccountList.xlsx:PatentRights", [], [], ["知的財産権", "研究開発費"]),
    ("商標権", "しょうひょうけん", "quyền sở hữu nhãn hiệu hàng hóa", "Quyền độc quyền sử dụng nhãn hiệu, logo đã được đăng ký xác lập quyền bảo hộ theo luật sở hữu trí tuệ.", "Trademark rights", "PRO-A2", 90, "1f_AccountList.xlsx:TrademarkRights", [], [], ["知的財産権", "ブランド"]),
    ("ソフトウェア", "そふとうぇあ", "phần mềm máy tính", "Các phần mềm nghiệp vụ mua ngoài hoặc tự phát triển phục vụ hoạt động nội bộ công ty.", "Software", "PRO-A1", 95, "1f_AccountList.xlsx:Software", [], [], ["自社利用ソフトウェア", "減価償却"]),
    ("借地権", "しゃくちけん", "quyền thuê đất dài hạn", "Quyền sử dụng đất của người khác để xây dựng công trình dựa trên hợp đồng thuê đất dài hạn.", "Right of leasehold", "PRO-A2", 87, "1f_AccountList.xlsx:RightOfLeasehold", [], [], ["土地", "権利金"]),
    ("投資有価証券", "とうしゆうかしょうけん", "chứng khoán đầu tư dài hạn", "Cổ phiếu, trái phiếu được doanh nghiệp nắm giữ với mục đích duy trì quan hệ kinh doanh lâu dài.", "Investment securities", "PRO-A2", 92, "1f_AccountList.xlsx:InvestmentSecurities", [], [], ["有価証券", "関係会社株式"]),
    ("関係会社株式", "かんけいがいしゃかぶしき", "cổ phiếu công ty con / liên kết", "Cổ phiếu do doanh nghiệp nắm giữ tại các công ty con hoặc công ty liên kết nhằm mục đích chi phối quản trị.", "Stocks of subsidiaries and associates", "PRO-A2", 91, "1f_AccountList.xlsx:StocksOfSubsidiariesAndAssociates", [], [], ["子会社", "連結決算"]),
    ("出資金", "しゅっしきん", "vốn góp đầu tư dài hạn", "Khoản tiền góp vốn vào các công ty TNHH, hợp danh, hợp tác xã không phát hành cổ phiếu.", "Investments in capital", "PRO-A2", 89, "1f_AccountList.xlsx:InvestmentsInCapital", [], [], ["投資その他の資産", "持分"]),
    ("長期貸付金", "ちょうきかしつけきん", "khoản cho vay dài hạn", "Khoản tiền cho các đơn vị thành viên, đối tác vay với thời hạn hoàn trả trên 1 năm.", "Long-term loans receivable", "PRO-A2", 89, "1f_AccountList.xlsx:LongTermLoansReceivable", [], ["短期貸付金"], ["受取利息", "固定負債"]),
    ("破産更生債権等", "はさんこうせいさいけんとう", "nợ phải thu khó đòi bị phá sản / tái cơ cấu", "Các khoản công nợ của những con nợ đã nộp đơn xin phá sản hoặc thủ tục phục hồi doanh nghiệp.", "Claims provable in bankruptcy", "PRO-A3", 88, "1f_AccountList.xlsx:ClaimsProvableInBankruptcy", [], [], ["貸倒損失", "貸倒引当金"]),
    ("敷金", "しききん", "tiền đặt cọc thuê trụ sở", "Số tiền doanh nghiệp đặt cọc cho chủ nhà khi ký hợp đồng thuê văn phòng và sẽ được hoàn lại.", "Leasehold deposits", "PRO-A1", 94, "1f_AccountList.xlsx:LeaseholdDeposits", [], [], ["保証金", "賃貸借契約"]),
    ("保証金", "ほしょうきん", "tiền ký quỹ bảo đảm", "Khoản tiền ký quỹ bảo đảm thực hiện hợp đồng giao dịch thương mại hoặc đại lý.", "Security deposits", "PRO-A1", 93, "1f_AccountList.xlsx:SecurityDeposits", [], [], ["敷金", "差入保証金"]),
    ("長期前払費用", "ちょうきまえばらいひよう", "chi phí trả trước dài hạn", "Các khoản chi phí đã trả trước có thời gian phân bổ vào chi phí trên 1 năm.", "Long-term prepaid expenses", "PRO-A2", 89, "1f_AccountList.xlsx:LongTermPrepaidExpenses", [], ["前払費用"], ["経過勘定"]),
    ("繰延資産", "くりのべしさん", "chi phí trả trước dài hạn chờ phân bổ", "Các khoản chi phí đã thực chi nhưng mang lại lợi ích cho nhiều niên độ kế toán tiếp theo.", "Deferred assets", "PRO-A3", 87, "1f_AccountList.xlsx:DeferredAssets", [], [], ["創立費", "開業費"]),
    ("創立費", "そうりつひ", "chi phí thành lập doanh nghiệp", "Các chi phí phát sinh trước khi công ty được đăng ký thành lập chính thức.", "Organization expenses", "PRO-A2", 88, "1f_AccountList.xlsx:OrganizationExpenses", [], [], ["開業費", "繰延資産"]),
    ("開業費", "かいぎょうひ", "chi phí chuẩn bị khai trương hoạt động", "Chi phí phát sinh từ thời điểm thành lập đến khi chính thức bắt đầu hoạt động kinh doanh thương mại.", "Pre-operating expenses", "PRO-A2", 88, "1f_AccountList.xlsx:PreOperatingExpenses", [], [], ["創立費", "繰延資産"]),
    ("固定資産除却損", "こていしさんじょきゃくそん", "lỗ do thanh lý hủy bỏ tài sản cố định", "Khoản lỗ phát sinh khi phá dỡ, loại bỏ hoàn toàn tài sản cố định khỏi sổ sách kế toán.", "Loss on retirement of non-current assets", "PRO-A2", 91, "1f_AccountList.xlsx:LossOnRetirementOfNonCurrentAssets", [], [], ["固定資産売却損", "特別損失"]),
    ("固定資産売却益", "こていしさんばいきゃくえき", "lãi do bán tài sản cố định", "Khoản lãi thu được khi giá chuyển nhượng tài sản cố định cao hơn giá trị ghi sổ còn lại của tài sản.", "Gain on sale of non-current assets", "PRO-A2", 91, "1f_AccountList.xlsx:GainOnSaleOfNonCurrentAssets", [], ["固定資産売却損"], ["特別利益"]),
    ("固定資産合計", "こていしさんごうけい", "tổng tài sản dài hạn", "Tổng giá trị của toàn bộ tài sản hữu hình, vô hình và các khoản đầu tư dài hạn.", "Total non-current assets", "PRO-A1", 94, "1f_AccountList.xlsx:TotalNonCurrentAssets", [], ["流動資産合計"], ["総資産"]),

    # --- 4. Current Liabilities (76-105) ---
    ("流動負債", "りゅうどうふさい", "nợ ngắn hạn", "Các nghĩa vụ nợ phải thanh toán trong vòng 1 năm hoặc trong 1 chu kỳ kinh doanh bình thường.", "Current liabilities", "PRO-A1", 97, "1f_AccountList.xlsx:CurrentLiabilities", [], ["固定負債"], ["流動資産", "流動比率"]),
    ("買掛金", "かいかけきん", "khoản phải trả người bán", "Khoản nợ phát sinh khi mua nguyên vật liệu, hàng hóa kinh doanh chính nhưng chưa trả tiền.", "Accounts payable - trade", "PRO-A1", 100, "1f_AccountList.xlsx:AccountsPayableTrade", ["仕入債務"], ["売掛金"], ["支払手形", "未払金"]),
    ("支払手形", "しはらいてがた", "thương phiếu phải trả", "Kỳ phiếu hoặc hối phiếu do doanh nghiệp ký phát cam kết sẽ trả tiền cho nhà cung cấp khi đến hạn.", "Notes payable - trade", "PRO-A2", 93, "1f_AccountList.xlsx:NotesPayableTrade", [], ["受取手形"], ["不渡り", "買掛金"]),
    ("電子記録債務", "でんしきろくさいむ", "chứng từ nợ điện tử phải trả", "Nghĩa vụ trả nợ được ghi nhận trên hệ thống đăng ký thanh toán điện tử thay thế cho hối phiếu giấy.", "Electronically recorded obligations - operating", "PRO-A2", 93, "1f_AccountList.xlsx:ElectronicallyRecordedObligationsOperating", [], ["電子記録債権"], ["支払手形", "買掛金"]),
    ("仕入債務", "しいれさいむ", "nợ phải trả thương mại", "Tổng các khoản nợ phải trả phát sinh từ việc mua hàng hóa kinh doanh chính (gồm 買掛金 và 支払手形).", "Trade payables", "PRO-A2", 94, "1f_AccountList.xlsx:NotesAndAccountsPayableTrade", [], ["売上債権"], ["買掛金", "支払手形"]),
    ("短期借入金", "たんきかりいれきん", "khoản vay ngân hàng ngắn hạn", "Khoản nợ vay ngân hàng hoặc tổ chức tín dụng có thời hạn trả nợ trong vòng 1 năm.", "Short-term borrowings", "PRO-A1", 96, "1f_AccountList.xlsx:ShortTermBorrowings", [], ["短期貸付金"], ["長期借入金", "支払利息"]),
    ("1年内返済予定の長期借入金", "いちねんないへんさいよていのちょうきかりいれきん", "nợ dài hạn đến hạn trả trong vòng 1 năm", "Phần nợ gốc của các khoản vay dài hạn có ngày đáo hạn phải thanh toán trong vòng 12 tháng tới.", "Current portion of long-term borrowings", "PRO-A2", 93, "1f_AccountList.xlsx:CurrentPortionOfLongTermBorrowings", [], [], ["長期借入金", "流動負債"]),
    ("未払金", "みばらいきん", "khoản phải trả khác", "Khoản tiền phải trả phát sinh từ việc mua sắm tài sản, dịch vụ ngoài hoạt động kinh doanh chính.", "Accounts payable - other", "PRO-A1", 96, "1f_AccountList.xlsx:AccountsPayableOther", [], ["未収入金"], ["買掛金", "未払費用"]),
    ("未払費用", "みばらいひよう", "chi phí phải trả / chi phí dồn tích", "Chi phí đã phát sinh do đã nhận dịch vụ liên tục trong kỳ nhưng chưa đến hạn thanh toán hợp đồng.", "Accrued expenses", "PRO-A2", 93, "1f_AccountList.xlsx:AccruedExpenses", [], ["前払費用"], ["経過勘定", "未払給与"]),
    ("未払法人税等", "みばらいほうじんぜいとう", "thuế thu nhập doanh nghiệp phải nộp", "Số thuế thu nhập doanh nghiệp, thuế cư trú, thuế kinh doanh tính trên lợi nhuận kỳ này chưa nộp.", "Income taxes payable", "PRO-A2", 95, "1f_AccountList.xlsx:IncomeTaxesPayable", [], [], ["法人税等", "確定申告"]),
    ("未払消費税等", "みばらいしょうひぜいとう", "thuế giá trị gia tăng / tiêu dùng phải nộp", "Chênh lệch giữa thuế tiêu dùng thu hộ từ khách và thuế tiêu dùng đã trả khi mua hàng phải nộp ngân sách.", "Consumption taxes payable", "PRO-A2", 95, "1f_AccountList.xlsx:AccruedConsumptionTaxes", [], [], ["消費税", "仕入税額控除"]),
    ("前受金", "まえうけきん", "tiền khách hàng trả trước", "Số tiền nhận trước từ khách hàng trước khi doanh nghiệp bàn giao hàng hóa hoặc cung cấp dịch vụ.", "Advances received", "PRO-A1", 95, "1f_AccountList.xlsx:AdvancesReceived", [], ["前渡金"], ["売上高", "契約負債"]),
    ("預り金", "あずかりきん", "tiền thu hộ, giữ hộ phải trả", "Khoản tiền doanh nghiệp giữ hộ của nhân viên hoặc bên thứ ba để nộp thay (như thuế TNCN khấu trừ, bảo hiểm).", "Deposits received", "PRO-A1", 96, "1f_AccountList.xlsx:DepositsReceived", [], [], ["源泉徴収", "社会保険料"]),
    ("前受収益", "まえうけしゅうえき", "doanh thu nhận trước chờ phân bổ", "Khoản doanh thu đã nhận tiền trước cho các dịch vụ sẽ cung cấp liên tục trong các kỳ sau.", "Deferred revenue / Unearned revenue", "PRO-A2", 89, "1f_AccountList.xlsx:DeferredRevenue", [], ["未収収益"], ["経過勘定"]),
    ("仮受金", "かりうけきん", "khoản tiền tạm thu chưa rõ nguyên nhân", "Khoản tiền đã chuyển vào tài khoản ngân hàng nhưng chưa xác định được nguồn gốc hoặc nội dung thanh toán.", "Suspense receipts", "PRO-A1", 93, "bookkeeping_foundation", [], ["仮払金"], ["消込", "入金照合"]),
    ("賞与引当金", "しょうよひきあてきん", "dự phòng tiền thưởng nhân viên", "Khoản trích trước chi phí tiền thưởng cho người lao động tương ứng với thời gian làm việc trong kỳ.", "Provision for bonuses", "PRO-A2", 94, "1f_AccountList.xlsx:ProvisionForBonuses", [], [], ["引当金", "給料手当"]),
    ("役員賞与引当金", "やくいんしょうよひきあてきん", "dự phòng tiền thưởng ban giám đốc / ban điều hành", "Khoản dự phòng trích lập để chi trả tiền thưởng cho thành viên Hội đồng quản trị và Ban giám đốc.", "Provision for directors' bonuses", "PRO-A2", 88, "1f_AccountList.xlsx:ProvisionForDirectorsBonuses", [], [], ["役員報酬", "株主総会"]),
    ("製品保証引当金", "せいひんほしょうひきあてきん", "dự phòng bảo hành sản phẩm", "Khoản trích trước chi phí sửa chữa, đổi trả bảo hành miễn phí cho sản phẩm đã bán ra trong kỳ.", "Provision for product warranties", "PRO-A2", 90, "1f_AccountList.xlsx:ProvisionForProductWarranties", [], [], ["アフターサービス", "売上原価"]),
    ("返金負債", "へんきんふさい", "nghĩa vụ hoàn trả tiền hàng", "Khoản nợ phải trả theo chuẩn doanh thu mới ước tính số tiền phải hoàn trả lại cho khách khi có hàng trả lại.", "Refund liabilities", "PRO-A3", 87, "1f_AccountList.xlsx:RefundLiabilities", [], [], ["収益認識", "契約負債"]),
    ("契約負債", "けいやくふさい", "nghĩa vụ thực hiện hợp đồng với khách hàng", "Nghĩa vụ phải chuyển giao hàng hóa dịch vụ cho khách khi đã nhận trước tiền hàng theo hợp đồng.", "Contract liabilities", "PRO-A3", 91, "1f_AccountList.xlsx:ContractLiabilities", [], ["契約資産"], ["収益認識基準", "前受金"]),
    ("流動負債合計", "りゅうどうふさいごうけい", "tổng nợ ngắn hạn", "Tổng cộng toàn bộ các khoản nợ phải trả trong vòng 1 năm của doanh nghiệp.", "Total current liabilities", "PRO-A1", 95, "1f_AccountList.xlsx:TotalCurrentLiabilities", [], ["流動資産合計"], ["固定負債合計"]),

    # --- 5. Non-Current Liabilities (97-115) ---
    ("固定負債", "こていふさい", "nợ dài hạn", "Các khoản nợ và nghĩa vụ tài chính có thời hạn hoàn trả trên 1 năm kể từ ngày khóa sổ.", "Non-current liabilities", "PRO-A1", 96, "1f_AccountList.xlsx:NonCurrentLiabilities", [], ["流動負債"], ["固定負債合計", "レバレッジ"]),
    ("長期借入金", "ちょうきかりいれきん", "khoản vay ngân hàng dài hạn", "Khoản nợ vay ngân hàng để đầu tư tài sản cố định hoặc bổ sung vốn với kỳ hạn trả nợ trên 1 năm.", "Long-term borrowings", "PRO-A1", 96, "1f_AccountList.xlsx:LongTermBorrowings", [], ["短期借入金"], ["支払利息", "担保"]),
    ("社債", "しゃさい", "trái phiếu công ty phát hành", "Chứng chỉ vay nợ do công ty cổ phần phát hành ra thị trường vốn để huy động tiền từ các nhà đầu tư.", "Bonds payable", "PRO-A2", 92, "1f_AccountList.xlsx:BondsPayable", [], [], ["社債利息", "社債発行費"]),
    ("退職給付引当金", "たいしょくきゅうふひきあてきん", "dự phòng trợ cấp thôi việc / hưu trí", "Khoản dự phòng trích trước để chuẩn bị chi trả chế độ trợ cấp thôi việc hoặc hưu trí cho nhân viên sau này.", "Provision for retirement benefits", "PRO-A2", 92, "1f_AccountList.xlsx:ProvisionForRetirementBenefits", [], [], ["退職給付費用", "年金資産"]),
    ("役員退職慰労引当金", "やくいんたいしょくいろうひきあてきん", "dự phòng tiền trợ cấp thôi việc cho ban điều hành", "Khoản dự phòng tích lũy để chi trả thù lao cống hiến khi thành viên hội đồng quản trị nghỉ hưu.", "Provision for directors' retirement benefits", "PRO-A3", 87, "1f_AccountList.xlsx:ProvisionForDirectorsRetirementBenefits", [], [], ["役員報酬", "引当金"]),
    ("資産除去債務", "しさんじょきょさいむ", "nghĩa vụ hoàn trả mặt bằng / tháo dỡ tài sản (ARO)", "Nghĩa vụ pháp lý phải hoàn trả lại hiện trạng ban đầu, tháo dỡ máy móc, xử lý môi trường khi dời tài sản.", "Asset retirement obligations", "PRO-A3", 89, "1f_AccountList.xlsx:AssetRetirementObligations", ["ARO"], [], ["有形固定資産", "原状回復"]),
    ("繰延税金負債", "くりのべぜいきんふさい", "nợ thuế thu nhập hoãn lại phải trả", "Khoản thuế thu nhập phải nộp trong tương lai do chênh lệch tạm thời chịu thuế phát sinh trong kỳ.", "Deferred tax liabilities", "PRO-A3", 90, "1f_AccountList.xlsx:DeferredTaxLiabilities", [], ["繰延税金資産"], ["税効果会計", "その他有価証券評価差額金"]),
    ("長期未払金", "ちょうきみばらいきん", "khoản phải trả dài hạn khác", "Khoản nợ mua sắm tài sản cố định có cam kết trả dần trong thời hạn trên 1 năm.", "Long-term accounts payable - other", "PRO-A2", 88, "1f_AccountList.xlsx:LongTermAccountsPayableOther", [], ["未払金"], ["固定負債"]),
    ("リース債務", "りーすさいむ", "nợ thuê tài chính", "Nghĩa vụ thanh toán tiền thuê tài sản phát sinh từ các hợp đồng thuê tài chính dài hạn.", "Lease obligations", "PRO-A2", 91, "1f_AccountList.xlsx:LeaseObligations", [], [], ["リース資産", "ファイナンス・リース"]),
    ("固定負債合計", "こていふさいごうけい", "tổng nợ dài hạn", "Tổng số nợ dài hạn gồm nợ vay ngân hàng dài hạn, trái phiếu và các khoản dự phòng dài hạn.", "Total non-current liabilities", "PRO-A1", 94, "1f_AccountList.xlsx:TotalNonCurrentLiabilities", [], ["流動負債合計"], ["負債合計"]),
    ("負債合計", "ふさいごうけい", "tổng nợ phải trả", "Tổng cộng toàn bộ nợ ngắn hạn và nợ dài hạn mà công ty có trách nhiệm thanh toán.", "Total liabilities", "PRO-A1", 97, "1f_AccountList.xlsx:TotalLiabilities", [], ["資産合計"], ["純資産合計"]),

    # --- 6. Equity & Net Assets (106-125) ---
    ("純資産の部", "じゅんしさんのぶ", "phần vốn chủ sở hữu và tài sản thuần", "Mục nằm bên phải bảng cân đối kế toán thể hiện quyền sở hữu ròng của các cổ đông sau khi trừ hết nợ.", "Net assets section", "PRO-A1", 96, "1f_AccountList.xlsx:NetAssetsSection", [], [], ["負債の部", "資産の部"]),
    ("株主資本", "かぶぬししほん", "vốn cổ đông", "Phần cốt lõi của vốn chủ sở hữu gồm vốn góp ban đầu, thặng dư vốn và lợi nhuận tích lũy giữ lại.", "Shareholders' equity", "PRO-A1", 97, "1f_AccountList.xlsx:ShareholdersEquity", [], [], ["資本金", "利益剰余金"]),
    ("資本金", "しほんきん", "vốn điều lệ / vốn góp cổ đông", "Số vốn ban đầu và các lần tăng vốn được các cổ đông góp vào công ty và đăng ký chính thức.", "Share capital / Capital stock", "PRO-A1", 99, "1f_AccountList.xlsx:CapitalStock", [], [], ["資本準備金", "増資"]),
    ("資本剰余金", "しほんじょうよきん", "thặng dư vốn cổ phần", "Khoản thặng dư phát sinh từ các giao dịch về vốn với cổ đông vượt quá mệnh giá vốn điều lệ.", "Capital surplus", "PRO-A2", 91, "1f_AccountList.xlsx:CapitalSurplus", [], [], ["資本準備金", "その他資本剰余金"]),
    ("資本準備金", "しほんじゅんびきん", "quỹ dự trữ bổ sung vốn điều lệ", "Khoản tiền trích lập bắt buộc theo Luật Doanh nghiệp từ phần tiền góp vốn vượt mệnh giá của cổ đông.", "Legal capital surplus", "PRO-A2", 91, "1f_AccountList.xlsx:LegalCapitalSurplus", [], [], ["資本金", "資本剰余金"]),
    ("その他資本剰余金", "そのたしほんじょうよきん", "thặng dư vốn khác", "Phần thặng dư vốn phát sinh từ việc giảm vốn điều lệ hoặc lãi lỗ từ việc bán cổ phiếu quỹ.", "Other capital surplus", "PRO-A3", 87, "1f_AccountList.xlsx:OtherCapitalSurplus", [], [], ["自己株式処分差益"]),
    ("利益剰余金", "りえきじょうよきん", "thặng dư lợi nhuận / lợi nhuận giữ lại", "Tổng số lợi nhuận tích lũy sau thuế qua các năm được công ty giữ lại để tái đầu tư.", "Retained earnings", "PRO-A1", 97, "1f_AccountList.xlsx:RetainedEarnings", ["内部留保"], [], ["利益準備金", "繰越利益剰余金"]),
    ("利益準備金", "りえきじゅんびきん", "quỹ dự trữ thặng dư lợi nhuận bắt buộc", "Quỹ bắt buộc phải trích lập tối thiểu 10% mỗi lần chia cổ tức cho đến khi đạt mức luật định.", "Legal retained earnings", "PRO-A2", 91, "1f_AccountList.xlsx:LegalRetainedEarnings", [], [], ["配当金", "利益剰余金"]),
    ("その他利益剰余金", "そのたりえきじょうよきん", "thặng dư lợi nhuận khác", "Phần thặng dư lợi nhuận có thể sử dụng tự do để chia cổ tức hoặc lập các quỹ theo ý chí đại hội cổ đông.", "Other retained earnings", "PRO-A2", 90, "1f_AccountList.xlsx:OtherRetainedEarnings", [], [], ["任意積立金", "繰越利益剰余金"]),
    ("繰越利益剰余金", "くりこしりえきじょうよきん", "lợi nhuận sau thuế chưa phân phối lũy kế", "Số dư lợi nhuận thuần lũy kế từ các năm trước chuyển sang sau khi đã trừ đi các khoản chia cổ tức.", "Retained earnings brought forward", "PRO-A1", 95, "1f_AccountList.xlsx:RetainedEarningsBroughtForward", [], [], ["当期純利益", "剰余金の配当"]),
    ("自己株式", "じこかぶしき", "cổ phiếu quỹ", "Cổ phiếu do chính công ty phát hành sau đó mua lại từ thị trường và ghi giảm trực tiếp trên vốn chủ sở hữu.", "Treasury shares", "PRO-A2", 93, "1f_AccountList.xlsx:TreasuryShares", ["金庫株"], [], ["自社株買い", "株主還元"]),
    ("その他有価証券評価差額金", "そのたゆうかしょうけんひょうかがくきん", "chênh lệch đánh giá lại chứng khoán sẵn sàng để bán", "Khoản lãi lỗ chưa thực hiện từ việc đánh giá lại theo giá thị trường của các chứng khoán đầu tư dài hạn.", "Valuation difference on available-for-sale securities", "PRO-A3", 89, "1f_AccountList.xlsx:ValuationDifferenceOnAvailableForSaleSecurities", [], [], ["その他有価証券", "税効果会計"]),
    ("繰延ヘッジ損益", "くりのべへっじそんえき", "lãi lỗ từ công cụ phòng ngừa rủi ro hoãn lại", "Lãi lỗ từ các hợp đồng phái sinh phòng ngừa rủi ro được hoãn ghi nhận cho đến khi tài sản cơ sở phát sinh.", "Deferred gains or losses on hedges", "PRO-A3", 88, "1f_AccountList.xlsx:DeferredGainsOrLossesOnHedges", [], [], ["デリバティブ", "ヘッジ会計"]),
    ("新株予約権", "しんかぶよやくけん", "quyền chọn mua cổ phiếu phát hành mới", "Quyền được mua cổ phiếu mới của công ty với mức giá xác định trước (như chứng quyền, stock option).", "Share acquisition rights", "PRO-A2", 91, "1f_AccountList.xlsx:ShareAcquisitionRights", ["ストックオプション"], [], ["株式報酬", "自己資本"]),
    ("純資産合計", "じゅんしさんごうけい", "tổng tài sản thuần", "Tổng cộng toàn bộ vốn cổ đông, các khoản chênh lệch đánh giá lại và quyền chọn mua cổ phiếu.", "Total net assets", "PRO-A1", 96, "1f_AccountList.xlsx:TotalNetAssets", [], [], ["総資産", "負債純資産合計"]),

    # --- 7. Revenues & Gross Profit (126-140) ---
    ("売上高", "うりあげだか", "doanh thu bán hàng / tổng doanh thu thuần", "Tổng số tiền thu được từ việc tiêu thụ hàng hóa hoặc cung cấp dịch vụ trong kỳ kinh doanh chính.", "Net sales / Revenue", "PRO-A1", 100, "1f_AccountList.xlsx:NetSales", ["売上"], [], ["売上原価", "売上総利益"]),
    ("完成工事高", "かんせいこうじだか", "doanh thu công trình xây dựng hoàn thành", "Khoản doanh thu được ghi nhận từ các hợp đồng xây dựng đã hoàn thành bàn giao cho chủ đầu tư.", "Net sales of completed construction contracts", "PRO-A2", 90, "1f_AccountList.xlsx:NetSalesOfCompletedConstructionContracts", [], [], ["完成工事原価", "工事進行基準"]),
    ("売上原価", "うりあげげんか", "giá vốn hàng bán (COGS)", "Toàn bộ chi phí sản xuất hoặc mua vào trực tiếp của lượng hàng hóa đã bán trong kỳ.", "Cost of sales", "PRO-A1", 99, "1f_AccountList.xlsx:CostOfSales", ["原価"], [], ["売上高", "売上総利益", "仕入高"]),
    ("期首商品棚卸高", "きしゅしょうひんたなおろしだか", "giá trị hàng tồn kho đầu kỳ", "Tổng giá trị hàng hóa tồn đọng từ kỳ trước chuyển sang để tiếp tục bán trong kỳ này.", "Beginning merchandise inventory", "PRO-A2", 92, "bookkeeping_foundation", [], [], ["当期商品仕入高", "期末商品棚卸高"]),
    ("当期商品仕入高", "とうきしょうひんしいれだか", "tổng giá trị mua hàng trong kỳ", "Tổng số tiền bỏ ra để mua hàng hóa phục vụ kinh doanh trong suốt kỳ kế toán hiện tại.", "Purchases of merchandise during the period", "PRO-A1", 94, "bookkeeping_foundation", [], [], ["仕入勘定", "売上原価"]),
    ("期末商品棚卸高", "きまつしょうひんたなおろしだか", "giá trị hàng tồn kho cuối kỳ", "Tổng giá trị hàng hóa còn tồn lại trong kho tại thời điểm kết thúc kỳ kế toán.", "Ending merchandise inventory", "PRO-A2", 93, "bookkeeping_foundation", [], [], ["実地棚卸", "売上原価"]),
    ("売上総利益", "うりあげそうりえき", "lợi nhuận gộp (lãi gộp)", "Chênh lệch giữa tổng doanh thu bán hàng và giá vốn hàng bán, phản ánh sức sinh lời của sản phẩm.", "Gross profit", "PRO-A1", 99, "1f_AccountList.xlsx:GrossProfit", ["粗利", "粗利益"], [], ["売上高", "営業利益"]),
    ("製造原価", "せいぞうげんか", "chi phí sản xuất chế tạo", "Tổng toàn bộ chi phí nguyên vật liệu, nhân công và chi phí chung phát sinh tại phân xưởng sản xuất.", "Cost of manufacturing", "PRO-A2", 94, "bookkeeping_foundation", [], [], ["製造原価報告書", "売上原価"]),
    ("材料費", "ざいりょうひ", "chi phí nguyên vật liệu", "Toàn bộ chi phí tiền mua vật liệu chính, vật liệu phụ, nhiên liệu tiêu hao trực tiếp cho sản xuất.", "Material costs", "PRO-A1", 95, "bookkeeping_foundation", [], [], ["直接材料費", "製造原価"]),
    ("労務費", "ろうむひ", "chi phí nhân công trực tiếp", "Tiền lương, tiền thưởng, bảo hiểm chi trả cho công nhân sản xuất trực tiếp tại nhà máy.", "Labor costs", "PRO-A1", 95, "bookkeeping_foundation", [], [], ["直接労務費", "製造原価"]),
    ("外注加工費", "がいちゅうかこうひ", "chi phí gia công thuê ngoài", "Chi phí trả cho các xưởng hoặc đối tác bên ngoài để thực hiện một phần công đoạn chế tạo sản phẩm.", "Outsourcing manufacturing costs", "PRO-A2", 92, "bookkeeping_foundation", [], [], ["製造経費", "外注費"]),
    ("製造間接費", "せいぞうかんせつひ", "chi phí sản xuất chung", "Các chi phí phát sinh tại phân xưởng không thể tính trực tiếp cho từng sản phẩm (như khấu hao máy móc xưởng).", "Manufacturing overhead", "PRO-A2", 93, "bookkeeping_foundation", [], [], ["配賦", "製造原価"]),
    ("完成工事原価", "かんせいこうじげんか", "giá thành công trình xây dựng hoàn thành", "Toàn bộ chi phí vật liệu, nhân công, máy thi công phát sinh cho công trình đã nghiệm thu.", "Cost of completed construction contracts", "PRO-A2", 90, "1f_AccountList.xlsx:CostOfCompletedConstructionContracts", [], [], ["完成工事高"]),
    ("完成工事総利益", "かんせいこうじそうりえき", "lợi nhuận gộp công trình xây dựng", "Lợi nhuận gộp thu được từ các hợp đồng thi công xây dựng hoàn thành.", "Gross profit on completed construction contracts", "PRO-A2", 89, "1f_AccountList.xlsx:GrossProfitOnCompletedConstructionContracts", [], [], ["完成工事高", "完成工事原価"]),
    ("営業収益", "えいぎょうしゅうえき", "doanh thu kinh doanh (ngành dịch vụ / vận tải)", "Tên gọi của chỉ tiêu doanh thu chính áp dụng cho các doanh nghiệp phi sản xuất như đường sắt, ngân hàng.", "Operating revenue", "PRO-A2", 92, "1f_AccountList.xlsx:OperatingRevenue", [], [], ["売上高", "営業利益"]),

    # --- 8. SG&A and Operating Expenses (141-170) ---
    ("販売費及び一般管理費", "はんばいひおよびいっぱんかんりひ", "chi phí bán hàng và quản lý doanh nghiệp (SG&A)", "Toàn bộ chi phí tiếp thị, bán hàng và chi phí vận hành bộ máy quản lý văn phòng của công ty.", "Selling, general and administrative expenses", "PRO-A1", 98, "1f_AccountList.xlsx:SellingGeneralAndAdministrativeExpenses", ["販管費", "SG&A"], [], ["営業利益", "役員報酬"]),
    ("役員報酬", "やくいんほうしゅう", "thù lao ban giám đốc / ban điều hành", "Khoản tiền thù lao cố định chi trả cho các thành viên Hội đồng quản trị và Ban điều hành.", "Directors' remuneration", "PRO-A1", 96, "1f_AccountList.xlsx:DirectorsRemuneration", [], [], ["定期同額給与", "損金算入"]),
    ("給料手当", "きゅうりょうてあて", "tiền lương và phụ cấp nhân viên", "Khoản tiền công, phụ cấp chức vụ, phụ cấp làm thêm giờ chi trả định kỳ cho người lao động.", "Salaries and allowances", "PRO-A1", 98, "1f_AccountList.xlsx:SalariesAndAllowances", ["給与"], [], ["賞与", "法定福利費"]),
    ("賞与", "しょうよ", "tiền thưởng định kỳ / bonus", "Khoản tiền thưởng chi trả cho nhân viên theo kết quả kinh doanh (thường vào mùa hè và mùa đông tại Nhật).", "Bonuses", "PRO-A1", 97, "1f_AccountList.xlsx:Bonuses", ["ボーナス"], [], ["賞与引当金", "給与"]),
    ("退職給付費用", "たいしょくきゅうふひよう", "chi phí trợ cấp hưu trí / thôi việc trong kỳ", "Chi phí phát sinh trong kỳ kế toán để tích lũy quỹ hưu trí và tiền thôi việc cho người lao động.", "Retirement benefit expenses", "PRO-A2", 91, "1f_AccountList.xlsx:RetirementBenefitExpenses", [], [], ["退職給付引当金"]),
    ("法定福利費", "ほうていふくりひ", "chi phí bảo hiểm bắt buộc theo luật định", "Phần tiền đóng bảo hiểm xã hội, bảo hiểm y tế, bảo hiểm thất nghiệp mà người sử dụng lao động bắt buộc phải nộp.", "Legal welfare expenses", "PRO-A1", 96, "1f_AccountList.xlsx:LegalWelfareExpenses", [], [], ["福利厚生費", "社会保険料"]),
    ("福利厚生費", "ふくりこうせいひ", "chi phí phúc lợi tự nguyện", "Các khoản chi bồi dưỡng sức khỏe, khám bệnh định kỳ, du lịch công ty, trợ cấp hiếu hỉ cho nhân viên.", "Welfare expenses", "PRO-A1", 95, "1f_AccountList.xlsx:WelfareExpenses", [], [], ["法定福利費", "社内行事"]),
    ("旅費交通費", "りょひこうつうひ", "chi phí đi lại và công tác", "Tiền vé tàu xe, máy bay, tiền khách sạn và phụ cấp công tác chi trả cho cán bộ công nhân viên.", "Travel and transportation expenses", "PRO-A1", 97, "1f_AccountList.xlsx:TravelAndTransportationExpenses", [], [], ["交通費精算", "出張"]),
    ("通信費", "つうしんひ", "chi phí bưu chính và viễn thông", "Tiền cước điện thoại, đường truyền internet, bưu phí gửi thư từ, chuyển phát nhanh phục vụ công việc.", "Communication expenses", "PRO-A1", 96, "1f_AccountList.xlsx:CommunicationExpenses", [], [], ["消耗品費", "インフラ"]),
    ("広告宣伝費", "こうこくせんでんひ", "chi phí quảng cáo và tiếp thị", "Chi phí chi trả cho các chiến dịch quảng cáo truyền hình, báo chí, mạng xã hội để quảng bá sản phẩm.", "Advertising expenses", "PRO-A1", 96, "1f_AccountList.xlsx:AdvertisingExpenses", [], [], ["販売促進費", "PR"]),
    ("販売促進費", "はんばいそくしんひ", "chi phí xúc tiến bán hàng / khuyến mại", "Chi phí làm hàng mẫu dùng thử, quà tặng kèm, tiền hoa hồng chiết khấu để kích thích sức mua.", "Sales promotion expenses", "PRO-A2", 93, "1f_AccountList.xlsx:SalesPromotionExpenses", ["販促費"], [], ["広告宣伝費"]),
    ("交際費", "こうさいひ", "chi phí tiếp khách và đối ngoại", "Khoản tiền chi trả cho việc mời cơm, quà biếu đối tác phục vụ việc duy trì và phát triển quan hệ làm ăn.", "Entertainment expenses", "PRO-A1", 97, "1f_AccountList.xlsx:EntertainmentExpenses", ["交際接待費"], [], ["損金不算入", "会食"]),
    ("会議費", "かいぎひ", "chi phí tổ chức hội họp", "Tiền nước uống, đồ ăn nhẹ, thuê phòng họp phục vụ các cuộc họp nội bộ hoặc họp với khách hàng.", "Meeting expenses", "PRO-A1", 95, "bookkeeping_foundation", [], [], ["交際費", "議事録"]),
    ("消耗品費", "しょうもうひんひ", "chi phí đồ dùng tiêu hao / văn phòng phẩm", "Chi phí mua sắm bút giấy, dụng cụ văn phòng, đồ dùng có thời gian sử dụng dưới 1 năm hoặc giá trị nhỏ.", "Supplies expenses", "PRO-A1", 98, "1f_AccountList.xlsx:SuppliesExpenses", [], [], ["工具器具備品", "事務用品"]),
    ("修繕費", "しゅうぜんひ", "chi phí sửa chữa và bảo dưỡng", "Chi phí bảo trì, sửa chữa định kỳ nhà xưởng, máy móc để duy trì khả năng hoạt động bình thường.", "Repair and maintenance expenses", "PRO-A1", 94, "1f_AccountList.xlsx:RepairAndMaintenanceExpenses", [], [], ["資本的支出", "設備保全"]),
    ("減価償却費", "げんかしょうきゃくひ", "chi phí khấu hao tài sản cố định", "Khoản chi phí phân bổ dần giá trị tài sản cố định vào chi phí từng kỳ theo thời gian sử dụng hữu ích.", "Depreciation expense", "PRO-A1", 98, "1f_AccountList.xlsx:DepreciationExpense", [], [], ["耐用年数", "定額法", "定率法"]),
    ("地代家賃", "ちだいやちん", "chi phí thuê đất và thuê nhà xưởng", "Tiền thuê văn phòng làm việc, thuê kho bãi hoặc tiền thuê đất trả cho chủ bất động sản định kỳ.", "Rent expenses", "PRO-A1", 97, "1f_AccountList.xlsx:RentExpenses", [], [], ["敷金", "賃貸借契約"]),
    ("水道光熱費", "すいどうこうねつひ", "chi phí điện, nước và năng lượng", "Tiền điện, nước, khí đốt sử dụng cho văn phòng làm việc hoặc phục vụ hoạt động chung.", "Utilities expenses", "PRO-A1", 96, "1f_AccountList.xlsx:UtilitiesExpenses", [], [], ["製造経費", "インフラ"]),
    ("支払手数料", "しはらいてすうりょう", "phí dịch vụ thanh toán / hoa hồng phải trả", "Phí chuyển khoản ngân hàng, phí dịch vụ tư vấn pháp lý, phí môi giới giao dịch.", "Commission expenses", "PRO-A1", 97, "1f_AccountList.xlsx:CommissionExpenses", [], [], ["振込手数料", "業務委託費"]),
    ("保険料", "ほけんりょう", "phí bảo hiểm tài sản", "Tiền nộp phí bảo hiểm hỏa hoạn, bảo hiểm trách nhiệm công cộng, bảo hiểm xe cộ để phòng ngừa rủi ro.", "Insurance expenses", "PRO-A1", 95, "1f_AccountList.xlsx:InsuranceExpenses", [], [], ["前払費用", "損害保険"]),
    ("租税公課", "そぜいこうか", "thuế môn bài và các loại phí công quyền", "Các khoản thuế không tính trên thu nhập (thuế tài sản, thuế trước bạ, thuế xe) và lệ phí nhà nước.", "Taxes and public charges", "PRO-A1", 96, "1f_AccountList.xlsx:TaxesAndPublicCharges", [], [], ["固定資産税", "印紙税"]),
    ("貸倒引当金繰入", "かしだおれひきあてきんくりいれ", "chi phí trích lập dự phòng nợ khó đòi", "Khoản chi phí ghi nhận trong kỳ để hình thành hoặc bổ sung quỹ dự phòng nợ phải thu khó đòi.", "Provision of allowance for doubtful accounts", "PRO-A2", 93, "1f_AccountList.xlsx:ProvisionOfAllowanceForDoubtfulAccounts", [], [], ["貸倒引当金", "貸倒損失"]),
    ("貸倒損失", "かしだおれそんしつ", "tổn thất nợ khó đòi bị xóa nợ", "Khoản thiệt hại thực tế phát sinh khi một khoản nợ phải thu khách hàng chính thức không thể thu hồi được.", "Bad debts expense", "PRO-A2", 92, "1f_AccountList.xlsx:BadDebtsExpense", [], [], ["貸倒引当金", "回収不能"]),
    ("研究開発費", "けんきゅうかいはつひ", "chi phí nghiên cứu và phát triển (R&D)", "Toàn bộ chi phí nhân công, vật liệu, thí nghiệm nhằm phát minh công nghệ mới hoặc tạo sản phẩm mới.", "Research and development expenses", "PRO-A2", 94, "1f_AccountList.xlsx:ResearchAndDevelopmentExpenses", ["R&D費用"], [], ["特許権", "製品開発"]),
    ("業務委託費", "ぎょうむいたくひ", "chi phí gia công và thuê ngoài dịch vụ", "Chi phí trả cho các nhà thầu phụ, đơn vị chuyên môn bên ngoài thực hiện các dịch vụ hỗ trợ kinh doanh.", "Outsourcing expenses", "PRO-A1", 96, "bookkeeping_foundation", [], [], ["支払手数料", "外注費"]),
    ("雑費", "ざっぴ", "chi phí lặt vặt khác", "Các khoản chi tiêu giá trị nhỏ không thường xuyên không thể xếp vào các tài khoản chi phí cụ thể nào khác.", "Miscellaneous expenses", "PRO-A1", 94, "1f_AccountList.xlsx:MiscellaneousExpenses", [], [], ["消耗品費", "経理処理"]),
    ("営業利益", "えいぎょうりえき", "lợi nhuận thuần từ hoạt động kinh doanh (EBIT)", "Khoản lợi nhuận thu được trực tiếp từ ngành nghề kinh doanh cốt lõi của doanh nghiệp.", "Operating profit", "PRO-A1", 100, "1f_AccountList.xlsx:OperatingIncome", [], ["営業損失"], ["売上総利益", "経常利益"]),
    ("営業損失", "えいぎょうそんしつ", "lỗ thuần từ hoạt động kinh doanh", "Trường hợp chi phí bán hàng và quản lý vượt quá lợi nhuận gộp từ bán hàng.", "Operating loss", "PRO-A1", 93, "1f_AccountList.xlsx:OperatingLoss", [], ["営業利益"], ["営業赤字"]),
    ("営業外収益", "えいぎょうがいしゅうえき", "doanh thu hoạt động tài chính và hoạt động khác", "Các khoản thu nhập phát sinh ngoài hoạt động kinh doanh chính (lãi tiền gửi, cổ tức, chênh lệch tỷ giá).", "Non-operating income", "PRO-A2", 94, "1f_AccountList.xlsx:NonOperatingIncome", [], ["営業外費用"], ["受取利息", "為替差益"]),
    ("営業外費用", "えいぎょうがいひよう", "chi phí hoạt động tài chính và hoạt động khác", "Các khoản chi phí tài chính phát sinh ngoài kinh doanh chính (lãi tiền vay, lỗ chênh lệch tỷ giá).", "Non-operating expenses", "PRO-A2", 94, "1f_AccountList.xlsx:NonOperatingExpenses", [], ["営業外収益"], ["支払利息", "為替差損"]),

    # --- 9. Financial, Extraordinary & Net Profit (171-185) ---
    ("支払利息", "しはらいりそく", "chi phí lãi tiền vay", "Khoản tiền lãi phải trả cho các ngân hàng hoặc tổ chức tín dụng đối với các khoản nợ vay.", "Interest expenses", "PRO-A1", 97, "1f_AccountList.xlsx:InterestExpenses", [], ["受取利息"], ["営業外費用", "借入金"]),
    ("社債利息", "しゃさいりそく", "lãi trái phiếu phải trả", "Tiền lãi định kỳ trả cho các trái chủ nắm giữ trái phiếu do công ty phát hành.", "Interest on bonds", "PRO-A2", 90, "1f_AccountList.xlsx:InterestOnBonds", [], [], ["社債", "営業外費用"]),
    ("為替差益", "かわせさえき", "lãi chênh lệch tỷ giá hối đoái", "Khoản lãi phát sinh do biến động tỷ giá giữa đồng Yên và các ngoại tệ trong các giao dịch thanh toán quốc tế.", "Foreign exchange gains", "PRO-A2", 93, "1f_AccountList.xlsx:ForeignExchangeGains", [], ["為替差損"], ["外貨建取引", "為替予約"]),
    ("為替差損", "かわせさそん", "lỗ chênh lệch tỷ giá hối đoái", "Khoản lỗ phát sinh do biến động tỷ giá ngoại tệ làm giảm giá trị tiền thu về hoặc tăng số tiền phải trả.", "Foreign exchange losses", "PRO-A2", 93, "1f_AccountList.xlsx:ForeignExchangeLosses", [], ["為替差益"], ["外貨建取引", "円高・円安"]),
    ("経常利益", "けいじょうりえき", "lợi nhuận thường niên / thông thường", "Lợi nhuận kinh doanh cộng doanh thu tài chính trừ chi phí tài chính, phản ánh sức sinh lời tổng thể bình thường.", "Ordinary income / Recurring profit", "PRO-A1", 98, "1f_AccountList.xlsx:OrdinaryIncome", ["ケイツネ"], ["経常損失"], ["営業利益", "当期純利益"]),
    ("特別利益", "とくべつりえき", "thu nhập bất thường / bất khả kháng", "Các khoản thu nhập đột xuất không mang tính định kỳ hàng năm (như lãi bán đất đai, nhà xưởng).", "Extraordinary income", "PRO-A2", 92, "1f_AccountList.xlsx:ExtraordinaryIncome", [], ["特別損失"], ["固定資産売却益"]),
    ("特別損失", "とくべつそんしつ", "chi phí bất thường / tổn thất đột xuất", "Các khoản tổn thất đột xuất phát sinh ngoài dự kiến (như thiệt hại do thiên tai hỏa hoạn, lỗ giảm giá trị tài sản).", "Extraordinary losses", "PRO-A2", 92, "1f_AccountList.xlsx:ExtraordinaryLosses", [], ["特別利益"], ["減損損失", "災害損失"]),
    ("減損損失", "げんそんそんしつ", "lỗ do suy giảm giá trị tài sản cố định", "Khoản lỗ ghi nhận khi khả năng tạo tiền trong tương lai của tài sản cố định giảm sút nghiêm trọng.", "Impairment loss", "PRO-A3", 92, "1f_AccountList.xlsx:ImpairmentLoss", [], [], ["減損会計", "回収可能価額"]),
    ("税引前当期純利益", "ぜいびきまえとうきじゅんりえき", "lợi nhuận kế toán trước thuế (EBT)", "Khoản lợi nhuận thuần trong kỳ sau khi đã tính toàn bộ thu chi thông thường và đột xuất trước khi nộp thuế.", "Profit before income taxes", "PRO-A1", 97, "1f_AccountList.xlsx:IncomeBeforeIncomeTaxes", [], [], ["法人税等", "当期純利益"]),
    ("法人税等", "ほうじんぜいとう", "chi phí thuế thu nhập doanh nghiệp", "Tổng các loại thuế tính trên thu nhập chịu thuế của doanh nghiệp gồm thuế TNDN, thuế cư trú và thuế kinh doanh.", "Income taxes", "PRO-A1", 98, "1f_AccountList.xlsx:IncomeTaxesCurrent", [], [], ["法人税", "住民税", "事業税"]),
    ("法人税等調整額", "ほうじんぜいとうちょうせいがく", "chi phí thuế hoãn lại / điều chỉnh thuế", "Khoản điều chỉnh chi phí thuế theo kế toán thuế hoãn lại để khớp lợi nhuận kế toán với nghĩa vụ thuế.", "Income taxes - deferred", "PRO-A3", 90, "1f_AccountList.xlsx:IncomeTaxesDeferred", [], [], ["税効果会計", "繰延税金資産"]),
    ("当期純利益", "とうきじゅんりえき", "lợi nhuận ròng sau thuế / lãi ròng", "Số lợi nhuận cuối cùng thuộc về cổ đông sau khi đã khấu trừ đầy đủ toàn bộ chi phí và thuế trong kỳ.", "Net income / Profit", "PRO-A1", 100, "1f_AccountList.xlsx:ProfitLoss", ["純利益", "ボトムライン"], ["当期純損失"], ["税引前当期純利益", "配当金"]),
    ("包括利益", "ほうかつりえき", "tổng thu nhập toàn diện", "Tổng biến động của tài sản thuần trong kỳ từ các giao dịch không liên quan đến việc góp vốn hay rút vốn của cổ đông.", "Comprehensive income", "PRO-A3", 90, "1f_AccountList.xlsx:ComprehensiveIncome", [], [], ["包括利益計算書", "純利益"]),
    ("1株当たり当期純利益", "ひとかぶあたりとうきじゅんりえき", "thu nhập trên mỗi cổ phần (EPS)", "Chỉ số tài chính tính bằng lợi nhuận ròng chia cho số lượng cổ phiếu đang lưu hành.", "Earnings per share (EPS)", "PRO-A2", 95, "1f_AccountList.xlsx:EarningsPerShare", ["EPS"], [], ["株価収益率", "PER"]),
    ("自己資本当期純利益率", "じこしほんとうきじゅんりえきりつ", "tỷ suất sinh lời trên vốn chủ sở hữu (ROE)", "Chỉ số đo lường hiệu quả sử dụng vốn của cổ đông, tính bằng lợi nhuận ròng chia cho vốn chủ sở hữu.", "Return on equity (ROE)", "PRO-A2", 95, "jicpa_glossary", ["ROE"], [], ["ROA", "財務指標"]),

    # --- 10. Bookkeeping Mechanics & Auditing Standards (186-200) ---
    ("複式簿記", "ふくしきぼき", "kế toán kép", "Phương pháp kế toán ghi chép mọi nghiệp vụ kinh tế tài chính vào ít nhất hai tài khoản tương ứng Nợ và Có.", "Double-entry bookkeeping", "PRO-A1", 96, "bookkeeping_foundation", [], ["単式簿記"], ["仕訳", "借方", "貸方"]),
    ("仕訳", "しわけ", "bút toán kế toán / định khoản", "Thao tác phân tích nghiệp vụ tài chính phát sinh thành các cặp tài khoản Nợ và Có cân bằng nhau.", "Journal entry", "PRO-A1", 100, "bookkeeping_foundation", [], [], ["仕訳帳", "借方", "貸方"]),
    ("借方", "かりかた", "bên Nợ (trong kế toán)", "Phía bên trái của tài khoản kế toán, ghi nhận sự tăng tài sản, tăng chi phí hoặc giảm nợ và vốn.", "Debit (Dr.)", "PRO-A1", 99, "bookkeeping_foundation", [], ["貸方"], ["仕訳", "貸借一致"]),
    ("貸方", "かしかた", "bên Có (trong kế toán)", "Phía bên phải của tài khoản kế toán, ghi nhận sự tăng nợ phải trả, tăng vốn, phát sinh doanh thu hoặc giảm tài sản.", "Credit (Cr.)", "PRO-A1", 99, "bookkeeping_foundation", [], ["借方"], ["仕訳", "貸借平均"]),
    ("勘定科目", "かんじょうかもく", "tài khoản kế toán / tên danh mục kế toán", "Tên gọi danh mục thống nhất được dùng để phân loại và theo dõi các giao dịch tài chính.", "Account title", "PRO-A1", 100, "1f_AccountList.xlsx:AccountListHeader", [], [], ["仕訳", "勘定科目体系"]),
    ("総勘定元帳", "そうかんじょうもとちょう", "sổ cái tổng hợp các tài khoản", "Sổ kế toán trung tâm tập hợp toàn bộ các bút toán phát sinh trong kỳ theo từng tài khoản riêng biệt.", "General ledger (GL)", "PRO-A1", 96, "bookkeeping_foundation", ["元帳", "GL"], [], ["仕訳帳", "試算表"]),
    ("試算表", "しさんひょう", "bảng cân đối thử / bảng tổng hợp phát sinh", "Bảng biểu lập ra định kỳ để kiểm tra tính chính xác của việc ghi sổ cái dựa trên nguyên tắc cân bằng Nợ Có.", "Trial balance", "PRO-A1", 96, "bookkeeping_foundation", ["T/B"], [], ["合計残高試算表", "精算表"]),
    ("決算整理仕訳", "けっさんせいりしわけ", "các bút toán điều chỉnh cuối kỳ quyết toán", "Các bút toán thực hiện vào cuối niên độ để phân bổ chi phí, dồn tích doanh thu và trích lập dự phòng chính xác.", "Adjusting entries", "PRO-A2", 94, "bookkeeping_foundation", [], [], ["経過勘定", "棚卸減耗損"]),
    ("会計方針", "かいけいほうしん", "chính sách kế toán áp dụng", "Các nguyên tắc, cơ sở, quy ước, quy tắc và thực tiễn cụ thể được doanh nghiệp áp dụng để lập báo cáo tài chính.", "Accounting policies", "PRO-A2", 94, "asbj_accounting_standards", [], [], ["注記", "会計上の見積り"]),
    ("会計上の見積り", "かいけいじょうのみつもり", "ước tính kế toán", "Sự xác định giá trị gần đúng của một chỉ tiêu tài chính khi không có phương pháp đo lường chính xác tuyệt đối.", "Accounting estimates", "PRO-A3", 92, "asbj_accounting_standards", [], [], ["見積りの変更", "引当金"]),
    ("継続企業の前提", "けいぞくきぎょうのぜんてい", "giả định hoạt động liên tục (Going Concern)", "Giả định căn bản rằng doanh nghiệp sẽ tiếp tục hoạt động kinh doanh bình thường trong tương lai gần.", "Going concern assumption", "PRO-A2", 93, "jicpa_glossary", ["ゴーイングコンサーン"], [], ["監査意見", "有価証券報告書"]),
    ("内部統制", "ないぶとうせい", "kiểm soát nội bộ", "Quy trình do hội đồng quản trị và toàn thể nhân viên thực hiện nhằm bảo đảm tính hiệu quả, độ tin cậy của báo cáo.", "Internal control", "PRO-A2", 95, "jicpa_glossary", ["J-SOX"], [], ["内部統制報告書", "コンプライアンス"]),
    ("監査法人", "かんさほうじん", "công ty kiểm toán độc lập", "Pháp nhân gồm các kiểm toán viên công chứng (CPA) thành lập để thực hiện dịch vụ kiểm toán báo cáo tài chính.", "Audit firm", "PRO-A1", 96, "jicpa_glossary", [], [], ["公認会計士", "独立監査人"]),
    ("監査基準", "かんさきじゅん", "chuẩn mực kiểm toán", "Hệ thống các nguyên tắc, chuẩn mực nghề nghiệp mà kiểm toán viên bắt buộc phải tuân thủ khi kiểm toán.", "Auditing standards", "PRO-A2", 92, "jicpa_glossary", [], [], ["監査計画", "監査手続"]),
    ("無限定適正意見", "むげんていてきせいいけん", "ý kiến kiểm toán chấp nhận toàn phần", "Ý kiến cao nhất của kiểm toán viên khẳng định báo cáo tài chính đã phản ánh trung thực và hợp lý trên các khía cạnh trọng yếu.", "Unqualified opinion / Clean opinion", "PRO-A3", 94, "jicpa_glossary", ["適正意見"], ["不適正意見"], ["限定付適正意見", "意見不表明"]),
    ("限定付適正意見", "げんていつきてきせいいけん", "ý kiến kiểm toán chấp nhận từng phần có ngoại trừ", "Ý kiến kiểm toán xác nhận báo cáo tài chính trung thực ngoại trừ một số điểm hạn chế.", "Qualified opinion", "PRO-A3", 91, "jicpa_glossary", [], ["無限定適正意見"], ["不適正意見"]),
    ("不適正意見", "ふてきせいいけん", "ý kiến kiểm toán không chấp nhận / trái ngược", "Ý kiến kiểm toán khẳng định báo cáo tài chính có những sai sót trọng yếu ảnh hưởng nghiêm trọng.", "Adverse opinion", "PRO-A3", 90, "jicpa_glossary", [], ["無限定適正意見"], ["限定付適正意見"]),
    ("意見不表明", "いけんふひょうめい", "từ chối đưa ra ý kiến kiểm toán", "Kiểm toán viên không thể thu thập đầy đủ bằng chứng kiểm toán cần thiết để đưa ra kết luận.", "Disclaimer of opinion", "PRO-A3", 90, "jicpa_glossary", [], [], ["監査証拠", "監査範囲の制約"])
]

print(f"Total defined accounting entries: {len(ACCOUNTING_DEFINITIONS)}")
assert len(ACCOUNTING_DEFINITIONS) == 200, f"Expected 200, got {len(ACCOUNTING_DEFINITIONS)}"

# Write out accounting.py
with open(OUT_FILE, "w", encoding="utf-8") as f:
    f.write('"""\nscripts/pilot_builder/accounting.py\nAuthoritative 200 canonical accounting learning entries.\n"""\n\n')
    f.write('ACCOUNTING_ITEMS = [\n')
    for item in ACCOUNTING_DEFINITIONS:
        surface, reading, vi_short, vi_exp, en_pref, tier, priority, src_ref, syns, ants, rels = item
        entry_dict = {
            "surface": surface,
            "reading": reading,
            "vi_short": vi_short,
            "vi_explanation": vi_exp,
            "en_preferred": en_pref,
            "tier": tier,
            "priority": priority,
            "source_reference": src_ref,
            "synonyms": syns,
            "antonyms": ants,
            "related_terms": rels
        }
        f.write("    " + json.dumps(entry_dict, ensure_ascii=False) + ",\n")
    f.write(']\n')

print(f"[+] Wrote {len(ACCOUNTING_DEFINITIONS)} entries to {OUT_FILE.relative_to(BASE_DIR)}")
