"""
scripts/phase1_3a/catalogs/hr_catalog.py
Authoritative statutory HR, labor, and social insurance terminology catalog
from MHLW (厚生労働省) and Japan Pension Service (日本年金機構).
Covers Labor Standards, 36 Agreements, Wages, Leave, Social Insurance, and Pension Administration.
"""

HR_TERMS = [
    # Labor Standards & Working Hours
    {"term": "法定労働時間", "en": "Statutory working hours (40 hours per week / 8 hours per day)", "subdomain": "working_hours", "statute": "労働基準法第32条"},
    {"term": "所定労働時間", "en": "Prescribed working hours / Contractual working hours", "subdomain": "working_hours", "statute": "労働契約法"},
    {"term": "所定外労働", "en": "Work outside prescribed hours", "subdomain": "working_hours", "statute": "労働基準法"},
    {"term": "時間外労働", "en": "Overtime work", "subdomain": "working_hours", "statute": "労働基準法第36条"},
    {"term": "休日労働", "en": "Holiday work", "subdomain": "working_hours", "statute": "労働基準法第35条"},
    {"term": "深夜労働", "en": "Late-night work (10 p.m. to 5 a.m.)", "subdomain": "working_hours", "statute": "労働基準法第61条"},
    {"term": "36協定", "en": "Article 36 Agreement (overtime work agreement)", "subdomain": "working_hours", "statute": "労働基準法第36条"},
    {"term": "特別条項付き36協定", "en": "Article 36 Agreement with special limitation extension clauses", "subdomain": "working_hours", "statute": "労働基準法第36条第5項"},
    {"term": "時間外労働の上限規制", "en": "Statutory cap on overtime work hours", "subdomain": "working_hours", "statute": "労働基準法第36条"},
    {"term": "変形労働時間制", "en": "Variable / Irregular working hours system", "subdomain": "working_hours", "statute": "労働基準法第32条の2"},
    {"term": "1箇月単位の変形労働時間制", "en": "One-month variable working hours system", "subdomain": "working_hours", "statute": "労働基準法第32条の2"},
    {"term": "1年単位の変形労働時間制", "en": "One-year variable working hours system", "subdomain": "working_hours", "statute": "労働基準法第32条の4"},
    {"term": "フレックスタイム制", "en": "Flextime system", "subdomain": "working_hours", "statute": "労働基準法第32条の3"},
    {"term": "コアタイム", "en": "Core working hours (flextime)", "subdomain": "working_hours", "statute": "労働基準法"},
    {"term": "フレキシブルタイム", "en": "Flexible hours band (flextime)", "subdomain": "working_hours", "statute": "労働基準法"},
    {"term": "清算期間", "en": "Settlement period (flextime system)", "subdomain": "working_hours", "statute": "労働基準法第32条の3"},
    {"term": "裁量労働制", "en": "Discretionary work system", "subdomain": "working_hours", "statute": "労働基準法第38条の3"},
    {"term": "専門業務型裁量労働制", "en": "Discretionary work system for professional services", "subdomain": "working_hours", "statute": "労働基準法第38条の3"},
    {"term": "企画業務型裁量労働制", "en": "Discretionary work system for planning and strategic operations", "subdomain": "working_hours", "statute": "労働基準法第38条の4"},
    {"term": "事業場外みなし労働時間制", "en": "Deemed working hours system for off-site work", "subdomain": "working_hours", "statute": "労働基準法第38条の2"},
    {"term": "高度プロフェッショナル制度", "en": "High-level professional exemption system", "subdomain": "working_hours", "statute": "労働基準法第41条の2"},
    {"term": "管理監督者", "en": "Managerial supervisor exempt from statutory hours", "subdomain": "working_hours", "statute": "労働基準法第41条第2号"},
    {"term": "休憩時間", "en": "Statutory rest period / Rest break", "subdomain": "working_hours", "statute": "労働基準法第34条"},
    {"term": "法定休日", "en": "Statutory day off / Mandatory weekly rest day", "subdomain": "working_hours", "statute": "労働基準法第35条"},
    {"term": "所定休日", "en": "Prescribed contractual non-working day", "subdomain": "working_hours", "statute": "労働基準法"},
    {"term": "振替休日", "en": "Transferred day off (prior scheduled exchange)", "subdomain": "working_hours", "statute": "労働基準法通達"},
    {"term": "代休", "en": "Compensatory day off (granted after working on a day off)", "subdomain": "working_hours", "statute": "労働基準法通達"},
    # Leave & Absences (休暇・休業)
    {"term": "年次有給休暇", "en": "Annual paid leave", "subdomain": "leave", "statute": "労働基準法第39条"},
    {"term": "有給休暇取得義務", "en": "Mandatory 5-day annual paid leave utilization duty", "subdomain": "leave", "statute": "労働基準法第39条第7項"},
    {"term": "計画的付与", "en": "Planned grant of annual paid leave by collective agreement", "subdomain": "leave", "statute": "労働基準法第39条第6項"},
    {"term": "時間単位年休", "en": "Hourly paid annual leave", "subdomain": "leave", "statute": "労働基準法第39条第4項"},
    {"term": "産前産後休業", "en": "Maternity leave (prenatal and postnatal leave)", "subdomain": "leave", "statute": "労働基準法第65条"},
    {"term": "育児休業", "en": "Childcare leave", "subdomain": "leave", "statute": "育児・介護休業法第5条"},
    {"term": "産後パパ育休", "en": "Postnatal childcare leave for fathers (paternity leave)", "subdomain": "leave", "statute": "育児・介護休業法第9条の2"},
    {"term": "出生時育児休業", "en": "Childcare leave at birth (paternity leave)", "subdomain": "leave", "statute": "育児・介護休業法"},
    {"term": "子の看護休暇", "en": "Nursing care leave for sick children", "subdomain": "leave", "statute": "育児・介護休業法第16条の2"},
    {"term": "介護休業", "en": "Family nursing care leave", "subdomain": "leave", "statute": "育児・介護休業法第11条"},
    {"term": "介護休暇", "en": "Short-term family care leave", "subdomain": "leave", "statute": "育児・介護休業法第16条の5"},
    {"term": "慶弔休暇", "en": "Condolence and congratulatory leave", "subdomain": "leave", "statute": "就業規則"},
    {"term": "生理休暇", "en": "Menstrual leave", "subdomain": "leave", "statute": "労働基準法第68条"},
    {"term": "裁判員休暇", "en": "Citizen judge participation leave", "subdomain": "leave", "statute": "労働基準法第7条"},
    {"term": "休職", "en": "Administrative suspension / Leave of absence", "subdomain": "leave", "statute": "就業規則"},
    {"term": "復職", "en": "Reinstatement / Return to work after leave", "subdomain": "leave", "statute": "就業規則"},
    # Wages & Payroll (給与・賃金)
    {"term": "割増賃金", "en": "Premium wages / Extra pay for overtime, holiday, and night work", "subdomain": "payroll", "statute": "労働基準法第37条"},
    {"term": "割増賃金率", "en": "Premium wage rate", "subdomain": "payroll", "statute": "労働基準法第37条"},
    {"term": "平均賃金", "en": "Average daily wage", "subdomain": "payroll", "statute": "労働基準法第12条"},
    {"term": "基本給", "en": "Base salary / Basic wage", "subdomain": "payroll", "statute": "労働契約"},
    {"term": "役職手当", "en": "Executive / Managerial position allowance", "subdomain": "payroll", "statute": "賃金規程"},
    {"term": "通勤手当", "en": "Commuting allowance", "subdomain": "payroll", "statute": "賃金規程"},
    {"term": "残業手当", "en": "Overtime allowance", "subdomain": "payroll", "statute": "労働基準法第37条"},
    {"term": "固定残業代", "en": "Fixed deemed overtime pay allowance", "subdomain": "payroll", "statute": "賃金規程"},
    {"term": "みなし残業手当", "en": "Deemed overtime allowance", "subdomain": "payroll", "statute": "賃金規程"},
    {"term": "賃金台帳", "en": "Wage ledger / Payroll register", "subdomain": "payroll", "statute": "労働基準法第108条"},
    {"term": "労働者名簿", "en": "Roster of workers / Employee roster", "subdomain": "employment", "statute": "労働基準法第107条"},
    {"term": "出勤簿", "en": "Attendance record / Time card book", "subdomain": "payroll", "statute": "労働安全衛生法"},
    {"term": "客観的な労働時間記録", "en": "Objective recording of working hours", "subdomain": "payroll", "statute": "労働安全衛生法第66条の8の3"},
    {"term": "賃金支払の5原則", "en": "Five principles of wage payment (currency, direct, full, monthly, fixed date)", "subdomain": "payroll", "statute": "労働基準法第24条"},
    {"term": "給与明細書", "en": "Pay slip / Salary specification statement", "subdomain": "payroll", "statute": "所得税法第231条"},
    {"term": "ノーワーク・ノーペイの原則", "en": "No work, no pay principle", "subdomain": "payroll", "statute": "民法第624条"},
    {"term": "欠勤控除", "en": "Absence deduction from salary", "subdomain": "payroll", "statute": "賃金規程"},
    {"term": "最低賃金", "en": "Statutory minimum wage", "subdomain": "payroll", "statute": "最低賃金法"},
    {"term": "地域別最低賃金", "en": "Regional minimum wage by prefecture", "subdomain": "payroll", "statute": "最低賃金法第9条"},
    # Employment Contracts & Dismissals (雇用契約・解雇・退職)
    {"term": "労働条件明示義務", "en": "Statutory obligation to clarify working conditions", "subdomain": "recruitment", "statute": "労働基準法第15条"},
    {"term": "労働条件通知書", "en": "Notice of working conditions", "subdomain": "recruitment", "statute": "労働基準法第15条"},
    {"term": "雇用契約書", "en": "Employment contract agreement", "subdomain": "recruitment", "statute": "労働契約法"},
    {"term": "試用期間", "en": "Probationary employment period", "subdomain": "recruitment", "statute": "労働基準法第20条"},
    {"term": "内定", "en": "Informal job offer / Tentative hiring decision", "subdomain": "recruitment", "statute": "労働契約実務"},
    {"term": "内定取消し", "en": "Revocation of tentative job offer", "subdomain": "recruitment", "statute": "労働契約法"},
    {"term": "無期転換ルール", "en": "Rule for conversion of fixed-term contract to open-ended employment", "subdomain": "employment", "statute": "労働契約法第18条"},
    {"term": "同一労働同一賃金", "en": "Equal pay for equal work principle", "subdomain": "employment", "statute": "パートタイム・有期雇用労働法第8条"},
    {"term": "就業規則", "en": "Rules of employment / Employee handbook", "subdomain": "employment", "statute": "労働基準法第89条"},
    {"term": "意見書", "en": "Written opinion of employee representative on rules of employment", "subdomain": "employment", "statute": "労働基準法第90条"},
    {"term": "労働者代表", "en": "Worker representative representing majority of employees", "subdomain": "employment", "statute": "労働基準法第90条"},
    {"term": "解雇予告", "en": "Advance notice of dismissal (30 days)", "subdomain": "employment", "statute": "労働基準法第20条"},
    {"term": "解雇予告手当", "en": "Allowance in lieu of notice of dismissal", "subdomain": "employment", "statute": "労働基準法第20条"},
    {"term": "整理解雇", "en": "Redundancy dismissal / Economic restructuring layoff", "subdomain": "employment", "statute": "労働契約法第16条"},
    {"term": "懲戒解雇", "en": "Disciplinary dismissal", "subdomain": "employment", "statute": "就業規則"},
    {"term": "普通解雇", "en": "Ordinary dismissal", "subdomain": "employment", "statute": "労働契約法第16条"},
    {"term": "解雇権濫用法理", "en": "Doctrine of abuse of dismissal rights", "subdomain": "employment", "statute": "労働契約法第16条"},
    {"term": "退職届", "en": "Notice of resignation", "subdomain": "employment", "statute": "民法第627条"},
    {"term": "退職願", "en": "Request for consensual termination of employment", "subdomain": "employment", "statute": "労働契約法"},
    {"term": "合意退職", "en": "Consensual termination of employment", "subdomain": "employment", "statute": "労働契約法"},
    {"term": "定年再雇用", "en": "Re-employment after mandatory retirement", "subdomain": "employment", "statute": "高年齢者雇用安定法"},
    {"term": "雇止め", "en": "Refusal to renew fixed-term employment contract", "subdomain": "employment", "statute": "労働契約法第19条"},
    # Social Insurance & Japan Pension Service (社会保険・日本年金機構)
    {"term": "標準報酬月額", "en": "Standard monthly remuneration (social insurance & pension calculation)", "subdomain": "social_insurance", "statute": "厚生年金保険法第20条"},
    {"term": "定時決定", "en": "Annual regular determination of standard remuneration", "subdomain": "social_insurance", "statute": "健康保険法第41条"},
    {"term": "算定基礎届", "en": "Annual report for calculation of standard monthly remuneration", "subdomain": "social_insurance", "statute": "厚生年金保険法第21条"},
    {"term": "随時改定", "en": "Ad hoc revision of standard remuneration (due to wage change)", "subdomain": "social_insurance", "statute": "健康保険法第43条"},
    {"term": "月額変更届", "en": "Notification of change in monthly remuneration", "subdomain": "social_insurance", "statute": "厚生年金保険法第23条"},
    {"term": "賞与支払届", "en": "Notification of payment of employee bonus", "subdomain": "social_insurance", "statute": "厚生年金保険法第24条の3"},
    {"term": "標準賞与額", "en": "Standard bonus amount", "subdomain": "social_insurance", "statute": "厚生年金保険法第24条の4"},
    {"term": "被保険者資格取得届", "en": "Notification of acquisition of insured person's qualification", "subdomain": "social_insurance", "statute": "健康保険法第48条"},
    {"term": "被保険者資格喪失届", "en": "Notification of loss of insured person's qualification", "subdomain": "social_insurance", "statute": "健康保険法第48条"},
    {"term": "被扶養者異動届", "en": "Notification of change / addition of dependent", "subdomain": "social_insurance", "statute": "健康保険法施行規則第38条"},
    {"term": "健康保険被保険者証", "en": "Health insurance certificate / Health insurance card", "subdomain": "social_insurance", "statute": "健康保険法"},
    {"term": "マイナ保険証", "en": "Individual Number card utilized as health insurance card", "subdomain": "social_insurance", "statute": "健康保険法"},
    {"term": "資格確認書", "en": "Certificate of eligibility confirmation (for non-MyNumber card holders)", "subdomain": "social_insurance", "statute": "健康保険法"},
    {"term": "社会保険料", "en": "Social insurance premiums", "subdomain": "social_insurance", "statute": "社会保険関係法令"},
    {"term": "労使折半", "en": "Equal sharing of premium payments between employer and employee", "subdomain": "social_insurance", "statute": "厚生年金保険法第82条"},
    {"term": "適用事業所", "en": "Covered workplace / Mandatory coverage business establishment", "subdomain": "social_insurance", "statute": "厚生年金保険法第6条"},
    {"term": "厚生年金基金", "en": "Employees' Pension Fund", "subdomain": "social_insurance", "statute": "厚生年金保険法"},
    {"term": "確定拠出年金", "en": "Defined contribution pension plan (DC / iDeCo)", "subdomain": "social_insurance", "statute": "確定拠出年金法"},
    {"term": "確定給付企業年金", "en": "Defined benefit corporate pension plan (DB)", "subdomain": "social_insurance", "statute": "確定給付企業年金法"},
    {"term": "傷病手当金", "en": "Injury and sickness allowance", "subdomain": "social_insurance", "statute": "健康保険法第99条"},
    {"term": "出産手当金", "en": "Maternity allowance during leave", "subdomain": "social_insurance", "statute": "健康保険法第102条"},
    {"term": "出産育児一時金", "en": "Lump-sum birth allowance", "subdomain": "social_insurance", "statute": "健康保険法第101条"},
    {"term": "高額療養費制度", "en": "High-cost medical expense benefit system", "subdomain": "social_insurance", "statute": "健康保険法第115条"},
    {"term": "埋葬料", "en": "Funeral expense benefit", "subdomain": "social_insurance", "statute": "健康保険法第100条"},
    # Labor Insurance (労働保険: 雇用保険 & 労災保険)
    {"term": "労働保険", "en": "Labor insurance (collective term for workers' comp and employment insurance)", "subdomain": "social_insurance", "statute": "労働保険徴収法"},
    {"term": "労働保険の保険料の徴収等に関する法律", "en": "Act on Collection of Premiums on Labor Insurance", "subdomain": "social_insurance", "statute": "法律"},
    {"term": "年度更新", "en": "Annual renewal of labor insurance premiums", "subdomain": "social_insurance", "statute": "労働保険徴収法第19条"},
    {"term": "概算保険料申告書", "en": "Estimated labor insurance premium return", "subdomain": "social_insurance", "statute": "労働保険徴収法第15条"},
    {"term": "確定保険料申告書", "en": "Final labor insurance premium return", "subdomain": "social_insurance", "statute": "労働保険徴収法第19条"},
    {"term": "雇用保険被保険者離職票", "en": "Employment insurance separation certificate for unemployed worker", "subdomain": "social_insurance", "statute": "雇用保険法施行規則第16条"},
    {"term": "離職証明書", "en": "Certificate of employment separation", "subdomain": "social_insurance", "statute": "雇用保険法施行規則第16条"},
    {"term": "基本手当", "en": "Basic unemployment allowance", "subdomain": "social_insurance", "statute": "雇用保険法第13条"},
    {"term": "雇用調整助成金", "en": "Employment adjustment subsidy", "subdomain": "social_insurance", "statute": "雇用保険法第62条"},
    {"term": "キャリアアップ助成金", "en": "Career advancement subsidy for non-regular workers", "subdomain": "social_insurance", "statute": "雇用保険法"},
    {"term": "育児休業給付金", "en": "Childcare leave benefits", "subdomain": "social_insurance", "statute": "雇用保険法第61条の4"},
    {"term": "出生時育児休業給付金", "en": "Childcare leave benefit at birth", "subdomain": "social_insurance", "statute": "雇用保険法第61条の8"},
    {"term": "介護休業給付金", "en": "Family nursing care leave benefits", "subdomain": "social_insurance", "statute": "雇用保険法第61条の6"},
    {"term": "高年齢雇用継続給付", "en": "Continuous employment benefits for elderly workers", "subdomain": "social_insurance", "statute": "雇用保険法第61条"},
    {"term": "労災保険", "en": "Industrial accident compensation insurance", "subdomain": "social_insurance", "statute": "労働者災害補償保険法"},
    {"term": "業務上災害", "en": "Occupational accident / Work-related accident", "subdomain": "labor_management", "statute": "労災保険法第7条第1項第1号"},
    {"term": "通勤災害", "en": "Commuting accident", "subdomain": "labor_management", "statute": "労災保険法第7条第1項第2号"},
    {"term": "休業補償給付", "en": "Compensation benefit for absence from work (workers' comp)", "subdomain": "social_insurance", "statute": "労災保険法第14条"},
    {"term": "療養補償給付", "en": "Compensation benefit for medical treatment (workers' comp)", "subdomain": "social_insurance", "statute": "労災保険法第13条"},
    {"term": "障害補償給付", "en": "Compensation benefit for permanent disability (workers' comp)", "subdomain": "social_insurance", "statute": "労災保険法第15条"},
    {"term": "遺族補償給付", "en": "Compensation benefit for surviving family (workers' comp)", "subdomain": "social_insurance", "statute": "労災保険法第16条"},
    {"term": "安全衛生委員会", "en": "Safety and Health Committee", "subdomain": "labor_management", "statute": "労働安全衛生法第19条"},
    {"term": "衛生管理者", "en": "Health supervisor / Industrial hygiene manager", "subdomain": "labor_management", "statute": "労働安全衛生法第12条"},
    {"term": "産業医", "en": "Occupational physician / Industrial doctor", "subdomain": "labor_management", "statute": "労働安全衛生法第13条"},
    {"term": "ストレスチェック", "en": "Psychological stress evaluation check", "subdomain": "labor_management", "statute": "労働安全衛生法第66条の10"},
    {"term": "定期健康診断", "en": "Periodic statutory health examination", "subdomain": "labor_management", "statute": "労働安全衛生法第66条"},
]
