"""
scripts/phase1_3a/catalogs/trade_catalog.py
Authoritative statutory and procedural trade, customs, and logistics catalog
from Japan Customs (財務省関税局), JETRO, and NACCS Center.
Covers Import/Export, Customs Clearance, Tariffs, HS Codes, Trade Documents, Incoterms, and Logistics.
"""

TRADE_TERMS = [
    # Customs & Import/Export Procedures (通関手続・輸出入)
    {"term": "輸出申告", "en": "Export declaration", "subdomain": "export", "statute": "関税法第67条"},
    {"term": "輸入申告", "en": "Import declaration", "subdomain": "import", "statute": "関税法第67条"},
    {"term": "輸出許可書", "en": "Export permit", "subdomain": "export", "statute": "関税法第67条"},
    {"term": "輸入許可書", "en": "Import permit", "subdomain": "import", "statute": "関税法第67条"},
    {"term": "通関手続", "en": "Customs clearance procedures", "subdomain": "customs_clearance", "statute": "関税法"},
    {"term": "通関士", "en": "Registered customs specialist / Customs broker", "subdomain": "customs_clearance", "statute": "通関業法第2条"},
    {"term": "通関業法", "en": "Customs Brokerage Act", "subdomain": "customs_clearance", "statute": "法律"},
    {"term": "申告納税方式", "en": "Self-assessment system of customs duties", "subdomain": "tariff", "statute": "関税法第7条"},
    {"term": "賦課課税方式", "en": "Official assessment system of customs duties", "subdomain": "tariff", "statute": "関税法第7条の2"},
    {"term": "関税定率法", "en": "Customs Tariff Act", "subdomain": "tariff", "statute": "法律"},
    {"term": "関税暫定措置法", "en": "Temporary Tariff Measures Act", "subdomain": "tariff", "statute": "法律"},
    {"term": "実行関税率表", "en": "Customs Tariff Schedule of Japan", "subdomain": "tariff", "statute": "関税定率法別表"},
    {"term": "品目分類", "en": "Tariff classification of goods", "subdomain": "tariff", "statute": "関税定率法"},
    {"term": "事前教示制度", "en": "Advance ruling system on tariff classification and customs valuation", "subdomain": "tariff", "statute": "関税法通達"},
    {"term": "課税価格", "en": "Customs value / Dutiable value", "subdomain": "tariff", "statute": "関税定率法第4条"},
    {"term": "CIF価格", "en": "Cost, Insurance and Freight value (customs valuation base)", "subdomain": "tariff", "statute": "関税定率法第4条"},
    {"term": "FOB価格", "en": "Free on Board value", "subdomain": "tariff", "statute": "関税定率法"},
    {"term": "特恵関税", "en": "Preferential tariff", "subdomain": "tariff", "statute": "関税暫定措置法第8条"},
    {"term": "一般特恵関税制度", "en": "Generalized System of Preferences (GSP)", "subdomain": "tariff", "statute": "関税暫定措置法"},
    {"term": "協定税率", "en": "WTO bound tariff rate", "subdomain": "tariff", "statute": "関税定率法"},
    {"term": "EPA税率", "en": "Economic Partnership Agreement preferential tariff rate", "subdomain": "tariff", "statute": "経済連携協定"},
    {"term": "暫定税率", "en": "Temporary tariff rate", "subdomain": "tariff", "statute": "関税暫定措置法"},
    {"term": "国定税率", "en": "General statutory tariff rate", "subdomain": "tariff", "statute": "関税定率法"},
    {"term": "原産地規則", "en": "Rules of origin", "subdomain": "origin", "statute": "関税法施行令第4条の2"},
    {"term": "完全生産品", "en": "Wholly obtained goods", "subdomain": "origin", "statute": "原産地規則"},
    {"term": "実質的変更基準", "en": "Substantial transformation criterion", "subdomain": "origin", "statute": "原産地規則"},
    {"term": "関税分類変更基準", "en": "Change in tariff classification criterion (CTC)", "subdomain": "origin", "statute": "原産地規則"},
    {"term": "付加価値基準", "en": "Regional value content criterion (RVC)", "subdomain": "origin", "statute": "原産地規則"},
    {"term": "原産地証明書", "en": "Certificate of Origin (C/O)", "subdomain": "origin", "statute": "関税法第68条"},
    {"term": "特定原産地証明書", "en": "Specified Certificate of Origin for EPA preferential rates", "subdomain": "origin", "statute": "経済連携協定法第3条"},
    {"term": "自己証明制度", "en": "Importer/Producer self-certification system of origin", "subdomain": "origin", "statute": "経済連携協定"},
    # AEO & Bonded Facilities (AEO制度・保税地域)
    {"term": "AEO制度", "en": "Authorized Economic Operator program", "subdomain": "customs_clearance", "statute": "関税法"},
    {"term": "認定通関業者", "en": "Authorized Customs Broker (AEO broker)", "subdomain": "customs_clearance", "statute": "関税法第79条の2"},
    {"term": "特定輸出者", "en": "Authorized Exporter (AEO exporter)", "subdomain": "export", "statute": "関税法第67条の3"},
    {"term": "特定輸入者", "en": "Authorized Importer (AEO importer)", "subdomain": "import", "statute": "関税法第7条の2"},
    {"term": "保税地域", "en": "Bonded area / Customs area", "subdomain": "customs_clearance", "statute": "関税法第29条"},
    {"term": "指定保税地域", "en": "Designated bonded area", "subdomain": "customs_clearance", "statute": "関税法第37条"},
    {"term": "保税蔵置場", "en": "Bonded warehouse", "subdomain": "customs_clearance", "statute": "関税法第42条"},
    {"term": "保税工場", "en": "Bonded manufacturing warehouse", "subdomain": "customs_clearance", "statute": "関税法第56条"},
    {"term": "保税展示場", "en": "Bonded exhibition site", "subdomain": "customs_clearance", "statute": "関税法第62条の2"},
    {"term": "総合保税地域", "en": "Integrated bonded area", "subdomain": "customs_clearance", "statute": "関税法第62条の8"},
    {"term": "保税運送", "en": "Bonded transportation", "subdomain": "customs_clearance", "statute": "関税法第63条"},
    {"term": "税関検査", "en": "Customs physical inspection of goods", "subdomain": "customs_clearance", "statute": "関税法第67条"},
    {"term": "他法令確認", "en": "Confirmation of permits under other laws and regulations", "subdomain": "customs_clearance", "statute": "関税法第70条"},
    {"term": "外国為替及び外国貿易法", "en": "Foreign Exchange and Foreign Trade Act (FEFTA)", "subdomain": "export", "statute": "法律"},
    {"term": "外為法", "en": "Foreign Exchange and Foreign Trade Act (abbreviation)", "subdomain": "export", "statute": "外為法"},
    {"term": "リスト規制", "en": "List-based export control on sensitive and military goods", "subdomain": "export", "statute": "輸出貿易管理令別表第一"},
    {"term": "キャッチオール規制", "en": "Catch-all export controls on dual-use items", "subdomain": "export", "statute": "輸出貿易管理令"},
    {"term": "該非判定", "en": "Jurisdiction / Applicability determination for strategic export control", "subdomain": "export", "statute": "外為法実務"},
    {"term": "輸出管理内部規程", "en": "Internal compliance program for security export control (CP)", "subdomain": "export", "statute": "経済産業省指針"},
    # Trade Documentation (貿易書類)
    {"term": "商業送り状", "en": "Commercial invoice", "subdomain": "trade_documents", "statute": "貿易実務"},
    {"term": "仕向書", "en": "Commercial invoice (traditional Japanese trade term)", "subdomain": "trade_documents", "statute": "貿易実務"},
    {"term": "梱包明細書", "en": "Packing list", "subdomain": "trade_documents", "statute": "貿易実務"},
    {"term": "船荷証券", "en": "Bill of Lading (B/L)", "subdomain": "trade_documents", "statute": "商法第757条"},
    {"term": "海上運送状", "en": "Sea Waybill", "subdomain": "trade_documents", "statute": "国際運送実務"},
    {"term": "航空貨物運送状", "en": "Air Waybill (AWB)", "subdomain": "trade_documents", "statute": "国際航空運送条約"},
    {"term": "貨物保険証券", "en": "Marine cargo insurance policy", "subdomain": "trade_documents", "statute": "保険法"},
    {"term": "信用状", "en": "Letter of Credit (L/C)", "subdomain": "trade_finance", "statute": "UCP600 信用状統一規則"},
    {"term": "荷為替手形", "en": "Documentary bill of exchange", "subdomain": "trade_finance", "statute": "手形法"},
    {"term": "支払渡し", "en": "Documents against Payment (D/P)", "subdomain": "trade_finance", "statute": "URC522 荷為替手形取立統一規則"},
    {"term": "引受渡し", "en": "Documents against Acceptance (D/A)", "subdomain": "trade_finance", "statute": "URC522 荷為替手形取立統一規則"},
    {"term": "電信送金", "en": "Telegraphic Transfer (T/T)", "subdomain": "trade_finance", "statute": "銀行為替実務"},
    {"term": "コルレス契約", "en": "Correspondent banking agreement", "subdomain": "trade_finance", "statute": "国際金融実務"},
    {"term": "船積指図書", "en": "Shipping Instructions (S/I)", "subdomain": "trade_documents", "statute": "国際物流実務"},
    {"term": "荷渡指図書", "en": "Delivery Order (D/O)", "subdomain": "shipping", "statute": "商法"},
    {"term": "海運貨物受取書", "en": "Mate's Receipt (M/R)", "subdomain": "shipping", "statute": "海商法"},
    # Incoterms 2020 (取引条件)
    {"term": "インコタームズ", "en": "Incoterms (International Commercial Terms)", "subdomain": "incoterms", "statute": "ICC国際商業会議所"},
    {"term": "工場渡し", "en": "Ex Works (EXW)", "subdomain": "incoterms", "statute": "Incoterms 2020"},
    {"term": "運送人渡し", "en": "Free Carrier (FCA)", "subdomain": "incoterms", "statute": "Incoterms 2020"},
    {"term": "船側渡し", "en": "Free Alongside Ship (FAS)", "subdomain": "incoterms", "statute": "Incoterms 2020"},
    {"term": "本船甲板渡し", "en": "Free on Board (FOB)", "subdomain": "incoterms", "statute": "Incoterms 2020"},
    {"term": "運賃込み条件", "en": "Cost and Freight (CFR)", "subdomain": "incoterms", "statute": "Incoterms 2020"},
    {"term": "運賃保険料込み条件", "en": "Cost, Insurance and Freight (CIF)", "subdomain": "incoterms", "statute": "Incoterms 2020"},
    {"term": "輸送費込み条件", "en": "Carriage Paid To (CPT)", "subdomain": "incoterms", "statute": "Incoterms 2020"},
    {"term": "輸送費保険料込み条件", "en": "Carriage and Insurance Paid To (CIP)", "subdomain": "incoterms", "statute": "Incoterms 2020"},
    {"term": "仕向地持込渡し", "en": "Delivered at Place (DAP)", "subdomain": "incoterms", "statute": "Incoterms 2020"},
    {"term": "荷卸込持込渡し", "en": "Delivered at Place Unloaded (DPU)", "subdomain": "incoterms", "statute": "Incoterms 2020"},
    {"term": "関税込持込渡し", "en": "Delivered Duty Paid (DDP)", "subdomain": "incoterms", "statute": "Incoterms 2020"},
    # Logistics, Shipping & Charges (国際物流・運賃諸掛)
    {"term": "コンテナヤード", "en": "Container Yard (CY)", "subdomain": "shipping", "statute": "港湾物流実務"},
    {"term": "コンテナフレイトステーション", "en": "Container Freight Station (CFS)", "subdomain": "shipping", "statute": "港湾物流実務"},
    {"term": "FCL貨物", "en": "Full Container Load cargo", "subdomain": "shipping", "statute": "国際海上運送"},
    {"term": "LCL貨物", "en": "Less than Container Load cargo (consolidated)", "subdomain": "shipping", "statute": "国際海上運送"},
    {"term": "混載貨物", "en": "Consolidated cargo", "subdomain": "shipping", "statute": "国際運送実務"},
    {"term": "フォワーダー", "en": "Freight forwarder / International freight agent", "subdomain": "shipping", "statute": "貨物利用運送事業法"},
    {"term": "乙仲", "en": "Customs freight forwarder (traditional maritime term)", "subdomain": "shipping", "statute": "港湾運送実務"},
    {"term": "滞船料", "en": "Demurrage charge (container detention penalty in terminal)", "subdomain": "freight", "statute": "海運実務"},
    {"term": "返却遅延料", "en": "Detention charge (container late return penalty outside terminal)", "subdomain": "freight", "statute": "海運実務"},
    {"term": "燃料割増料", "en": "Bunker Adjustment Factor (BAF) / Fuel surcharge", "subdomain": "freight", "statute": "海運実務"},
    {"term": "為替変動調整因子", "en": "Currency Adjustment Factor (CAF)", "subdomain": "freight", "statute": "海運実務"},
    {"term": "ターミナルハンドリングチャージ", "en": "Terminal Handling Charge (THC)", "subdomain": "freight", "statute": "港湾物流実務"},
    # NACCS Operations (NACCS業務)
    {"term": "輸出入・港湾関連情報処理システム", "en": "Nippon Automated Cargo and Port Consolidated System (NACCS)", "subdomain": "customs_clearance", "statute": "NACCS法"},
    {"term": "NACCS", "en": "Nippon Automated Cargo and Port Consolidated System (acronym)", "subdomain": "customs_clearance", "statute": "NACCS法"},
    {"term": "業務コード", "en": "NACCS operation transaction code", "subdomain": "customs_clearance", "statute": "NACCS業務仕様"},
    {"term": "輸出申告入力", "en": "Export declaration entry (EDA in NACCS)", "subdomain": "export", "statute": "NACCS業務仕様"},
    {"term": "輸入申告入力", "en": "Import declaration entry (IDA in NACCS)", "subdomain": "import", "statute": "NACCS業務仕様"},
    {"term": "リアルタイム口座振替", "en": "Real-time bank account transfer for customs duty payment", "subdomain": "customs_clearance", "statute": "NACCS仕様"},
    {"term": "蔵出輸入申告", "en": "Declaration for import after storage in bonded warehouse (ISD)", "subdomain": "import", "statute": "関税法第67条"},
    {"term": "保税運送申告", "en": "Bonded transportation declaration (OLC in NACCS)", "subdomain": "customs_clearance", "statute": "関税法第63条"},
    {"term": "貨物搬入確認", "en": "Confirmation of cargo arrival in bonded facility", "subdomain": "customs_clearance", "statute": "関税法"},
    {"term": "区分1", "en": "Customs clearance Category 1 (instant electronic release without document review)", "subdomain": "customs_clearance", "statute": "税関審査区分"},
    {"term": "区分2", "en": "Customs clearance Category 2 (documentary examination required)", "subdomain": "customs_clearance", "statute": "税関審査区分"},
    {"term": "区分3", "en": "Customs clearance Category 3 (physical cargo inspection required)", "subdomain": "customs_clearance", "statute": "税関審査区分"},
]
