"""
scripts/phase1_3c/daily_lexicon.py
Curated High-Utility Daily English-Vietnamese Core Lexicon for Phase 1.3C.
Contains high-frequency daily vocabulary pairs verified against tabidots/vn-freqs (vn_word_frequencies.tsv).
"""

from typing import Dict, Tuple

# Mapping: ngsl_lemma -> (vi_word, pos, domain)
# Every vi_word here has been verified to exist in vn_word_frequencies.tsv
DAILY_EN_VI_CORE: Dict[str, Tuple[str, str, str]] = {
    # People & Family
    "person": ("người", "noun", "people"),
    "people": ("người", "noun", "people"),
    "man": ("đàn ông", "noun", "people"),
    "woman": ("phụ nữ", "noun", "people"),
    "child": ("trẻ em", "noun", "family"),
    "boy": ("cậu bé", "noun", "people"),
    "girl": ("gái", "noun", "people"),
    "baby": ("bé", "noun", "family"),
    "family": ("gia đình", "noun", "family"),
    "father": ("bố", "noun", "family"),
    "mother": ("mẹ", "noun", "family"),
    "parent": ("cha mẹ", "noun", "family"),
    "son": ("con trai", "noun", "family"),
    "daughter": ("con gái", "noun", "family"),
    "brother": ("anh em", "noun", "family"),
    "sister": ("chị em", "noun", "family"),
    "friend": ("bạn bè", "noun", "people"),
    "husband": ("chồng", "noun", "family"),
    "wife": ("vợ", "noun", "family"),

    # Body & Health
    "body": ("cơ thể", "noun", "health"),
    "head": ("đầu", "noun", "health"),
    "eye": ("mắt", "noun", "health"),
    "ear": ("tai", "noun", "health"),
    "nose": ("mũi", "noun", "health"),
    "mouth": ("miệng", "noun", "health"),
    "hand": ("tay", "noun", "health"),
    "foot": ("chân", "noun", "health"),
    "heart": ("tim", "noun", "health"),
    "blood": ("máu", "noun", "health"),
    "health": ("sức khoẻ", "noun", "health"),
    "disease": ("bệnh tật", "noun", "health"),
    "pain": ("đau đớn", "noun", "health"),
    "medicine": ("thuốc", "noun", "health"),

    # Daily Life & Objects
    "water": ("nước", "noun", "daily_life"),
    "food": ("thức ăn", "noun", "daily_life"),
    "bread": ("bánh mì", "noun", "daily_life"),
    "rice": ("cơm", "noun", "daily_life"),
    "meat": ("thịt", "noun", "daily_life"),
    "fish": ("cá", "noun", "daily_life"),
    "fruit": ("trái cây", "noun", "daily_life"),
    "vegetable": ("rau", "noun", "daily_life"),
    "tea": ("trà", "noun", "daily_life"),
    "coffee": ("cà phê", "noun", "daily_life"),
    "milk": ("sữa", "noun", "daily_life"),
    "salt": ("muối", "noun", "daily_life"),
    "sugar": ("đường", "noun", "daily_life"),
    "house": ("nhà", "noun", "home"),
    "home": ("nhà", "noun", "home"),
    "room": ("phòng", "noun", "home"),
    "door": ("cửa", "noun", "home"),
    "window": ("cửa sổ", "noun", "home"),
    "bed": ("giường", "noun", "home"),
    "table": ("bàn", "noun", "home"),
    "chair": ("ghế", "noun", "home"),
    "clothes": ("quần áo", "noun", "daily_life"),
    "shoe": ("giày", "noun", "daily_life"),
    "bag": ("túi", "noun", "daily_life"),
    "money": ("tiền", "noun", "daily_life"),
    "price": ("giá cả", "noun", "commerce"),

    # Nature & World
    "world": ("thế giới", "noun", "nature"),
    "earth": ("trái đất", "noun", "nature"),
    "country": ("đất nước", "noun", "society"),
    "city": ("thành phố", "noun", "society"),
    "town": ("thị trấn", "noun", "society"),
    "village": ("làng", "noun", "society"),
    "sun": ("mặt trời", "noun", "nature"),
    "moon": ("mặt trăng", "noun", "nature"),
    "star": ("sao", "noun", "nature"),
    "sky": ("bầu trời", "noun", "nature"),
    "air": ("không khí", "noun", "nature"),
    "sea": ("biển", "noun", "nature"),
    "ocean": ("đại dương", "noun", "nature"),
    "river": ("sông", "noun", "nature"),
    "mountain": ("núi", "noun", "nature"),
    "tree": ("cây", "noun", "nature"),
    "flower": ("hoa", "noun", "nature"),
    "animal": ("động vật", "noun", "nature"),
    "dog": ("chó", "noun", "nature"),
    "cat": ("mèo", "noun", "nature"),
    "bird": ("chim", "noun", "nature"),
    "weather": ("thời tiết", "noun", "nature"),
    "rain": ("mưa", "noun", "nature"),
    "snow": ("tuyết", "noun", "nature"),
    "wind": ("gió", "noun", "nature"),
    "fire": ("lửa", "noun", "nature"),

    # Time
    "time": ("thời gian", "noun", "time"),
    "year": ("năm", "noun", "time"),
    "month": ("tháng", "noun", "time"),
    "week": ("tuần", "noun", "time"),
    "day": ("ngày", "noun", "time"),
    "hour": ("giờ", "noun", "time"),
    "minute": ("phút", "noun", "time"),
    "second": ("giây", "noun", "time"),
    "morning": ("buổi sáng", "noun", "time"),
    "afternoon": ("chiều", "noun", "time"),
    "night": ("đêm", "noun", "time"),
    "today": ("hôm nay", "noun", "time"),
    "tomorrow": ("ngày mai", "noun", "time"),
    "yesterday": ("hôm qua", "noun", "time"),

    # Education & Work
    "school": ("trường học", "noun", "education"),
    "student": ("học sinh", "noun", "education"),
    "teacher": ("giáo viên", "noun", "education"),
    "class": ("lớp học", "noun", "education"),
    "book": ("sách", "noun", "education"),
    "paper": ("giấy", "noun", "education"),
    "letter": ("thư", "noun", "communication"),
    "word": ("từ", "noun", "language"),
    "language": ("ngôn ngữ", "noun", "language"),
    "work": ("công việc", "noun", "business"),
    "job": ("nghề nghiệp", "noun", "business"),
    "office": ("văn phòng", "noun", "business"),
    "market": ("chợ", "noun", "commerce"),
    "store": ("cửa hàng", "noun", "commerce"),
    "road": ("đường", "noun", "transport"),
    "street": ("đường phố", "noun", "transport"),
    "car": ("xe", "noun", "transport"),
    "bus": ("xe buýt", "noun", "transport"),
    "train": ("tàu", "noun", "transport"),
    "ship": ("tàu", "noun", "transport"),
    "plane": ("máy bay", "noun", "transport"),

    # Verbs - Actions & Movement
    "see": ("nhìn", "verb", "perception"),
    "look": ("nhìn", "verb", "perception"),
    "watch": ("xem", "verb", "perception"),
    "hear": ("nghe", "verb", "perception"),
    "listen": ("nghe", "verb", "perception"),
    "speak": ("nói", "verb", "communication"),
    "talk": ("nói chuyện", "verb", "communication"),
    "say": ("nói", "verb", "communication"),
    "tell": ("kể", "verb", "communication"),
    "ask": ("hỏi", "verb", "communication"),
    "answer": ("trả lời", "verb", "communication"),
    "read": ("đọc", "verb", "education"),
    "write": ("viết", "verb", "education"),
    "eat": ("ăn", "verb", "daily_life"),
    "drink": ("uống", "verb", "daily_life"),
    "sleep": ("ngủ", "verb", "daily_life"),
    "wake": ("dậy", "verb", "daily_life"),
    "go": ("đi", "verb", "motion"),
    "come": ("đến", "verb", "motion"),
    "walk": ("đi bộ", "verb", "motion"),
    "run": ("chạy", "verb", "motion"),
    "stop": ("dừng", "verb", "motion"),
    "stay": ("ở", "verb", "state"),
    "live": ("sống", "verb", "state"),
    "die": ("chết", "verb", "state"),
    "give": ("cho", "verb", "interaction"),
    "take": ("lấy", "verb", "interaction"),
    "bring": ("mang", "verb", "interaction"),
    "send": ("gửi", "verb", "interaction"),
    "receive": ("nhận", "verb", "interaction"),
    "buy": ("mua", "verb", "commerce"),
    "sell": ("bán", "verb", "commerce"),
    "pay": ("trả", "verb", "commerce"),
    "cost": ("giá", "verb", "commerce"),
    "open": ("mở", "verb", "action"),
    "close": ("đóng", "verb", "action"),
    "start": ("bắt đầu", "verb", "action"),
    "finish": ("hoàn thành", "verb", "action"),
    "help": ("giúp", "verb", "social"),
    "meet": ("gặp", "verb", "social"),
    "visit": ("thăm", "verb", "social"),
    "play": ("chơi", "verb", "leisure"),
    "sing": ("hát", "verb", "art"),
    "dance": ("nhảy múa", "verb", "art"),
    "laugh": ("cười", "verb", "emotion"),
    "cry": ("khóc", "verb", "emotion"),
    "smile": ("cười", "verb", "emotion"),
    "think": ("nghĩ", "verb", "cognition"),
    "know": ("biết", "verb", "cognition"),
    "understand": ("hiểu", "verb", "cognition"),
    "remember": ("nhớ", "verb", "cognition"),
    "forget": ("quên", "verb", "cognition"),
    "learn": ("học", "verb", "education"),
    "teach": ("dạy", "verb", "education"),
    "want": ("muốn", "verb", "volition"),
    "need": ("cần", "verb", "volition"),
    "like": ("thích", "verb", "emotion"),
    "love": ("yêu", "verb", "emotion"),
    "hope": ("hy vọng", "verb", "emotion"),
    "feel": ("cảm thấy", "verb", "perception"),

    # Adjectives
    "good": ("tốt", "adjective", "quality"),
    "bad": ("xấu", "adjective", "quality"),
    "great": ("tuyệt vời", "adjective", "quality"),
    "big": ("lớn", "adjective", "size"),
    "large": ("lớn", "adjective", "size"),
    "small": ("nhỏ", "adjective", "size"),
    "little": ("nhỏ", "adjective", "size"),
    "long": ("dài", "adjective", "dimension"),
    "short": ("ngắn", "adjective", "dimension"),
    "high": ("cao", "adjective", "dimension"),
    "low": ("thấp", "adjective", "dimension"),
    "hot": ("nóng", "adjective", "temperature"),
    "cold": ("lạnh", "adjective", "temperature"),
    "warm": ("ấm áp", "adjective", "temperature"),
    "cool": ("mát mẻ", "adjective", "temperature"),
    "new": ("mới", "adjective", "age"),
    "old": ("cũ", "adjective", "age"),
    "young": ("trẻ", "adjective", "age"),
    "fast": ("nhanh", "adjective", "speed"),
    "quick": ("nhanh chóng", "adjective", "speed"),
    "slow": ("chậm", "adjective", "speed"),
    "easy": ("dễ", "adjective", "difficulty"),
    "hard": ("khó", "adjective", "difficulty"),
    "difficult": ("khó khăn", "adjective", "difficulty"),
    "simple": ("đơn giản", "adjective", "complexity"),
    "clean": ("sạch", "adjective", "state"),
    "dirty": ("bẩn", "adjective", "state"),
    "full": ("đầy", "adjective", "state"),
    "empty": ("trống", "adjective", "state"),
    "happy": ("hạnh phúc", "adjective", "emotion"),
    "sad": ("buồn", "adjective", "emotion"),
    "rich": ("giàu", "adjective", "economics"),
    "poor": ("nghèo", "adjective", "economics"),
    "strong": ("mạnh", "adjective", "physical"),
    "weak": ("yếu", "adjective", "physical"),
    "true": ("thật", "adjective", "truth"),
    "false": ("sai", "adjective", "truth"),
    "safe": ("an toàn", "adjective", "safety"),
    "dangerous": ("nguy hiểm", "adjective", "safety"),
    "beautiful": ("đẹp", "adjective", "aesthetics"),
    "quiet": ("yên tĩnh", "adjective", "sensory"),
    "loud": ("ồn ào", "adjective", "sensory"),
    "bright": ("sáng", "adjective", "sensory"),
    "dark": ("tối", "adjective", "sensory"),
    "heavy": ("nặng", "adjective", "weight"),
    "light": ("nhẹ", "adjective", "weight"),
    "red": ("đỏ", "adjective", "color"),
    "blue": ("xanh", "adjective", "color"),
    "green": ("xanh", "adjective", "color"),
    "yellow": ("vàng", "adjective", "color"),
    "white": ("trắng", "adjective", "color"),
    "black": ("đen", "adjective", "color"),

    # Adverbs & Functional Words
    "always": ("luôn luôn", "adverb", "frequency"),
    "never": ("không", "adverb", "frequency"),
    "often": ("thường", "adverb", "frequency"),
    "sometimes": ("thỉnh thoảng", "adverb", "frequency"),
    "now": ("bây giờ", "adverb", "time"),
    "then": ("sau", "adverb", "time"),
    "here": ("đây", "adverb", "location"),
    "there": ("đó", "adverb", "location"),
    "very": ("rất", "adverb", "degree"),
    "too": ("quá", "adverb", "degree"),
    "well": ("tốt", "adverb", "manner"),
    "together": ("cùng", "adverb", "manner"),
    "again": ("lại", "adverb", "repetition")
}
